--- pyproject.toml.orig	2022-11-09 12:37:21 UTC
+++ pyproject.toml
@@ -1,7 +1,7 @@ requires = [
 [build-system]
 requires = [
     "scikit-build-core >=0.11",
-    "nanobind >=2, <3",
+    "nanobind >=2",
 
     "setuptools >=45",
     "setuptools_scm[toml] >=6.2",
@@ -56,6 +56,7 @@ Source = "https://github.com/dofuuz/python-soxr"
 "Bug Tracker" = "https://github.com/dofuuz/python-soxr/issues"
 
 [tool.scikit-build]
+cmake.version = ">=3.15"
 # Protect the configuration against future changes in scikit-build-core
 minimum-version = "build-system.requires"
 
