# $Id: Makefile,v 1.11 2005/08/26 22:44:38 cpressey Exp $

BASE?=../../..
include ${BASE}/Config

all:
clean:

install:
	mkdir -p ${DESTDIR}${PREFIX}/share/lua/5.0
	cp transceiver.lua ${DESTDIR}${PREFIX}/share/lua/5.0
