# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	ngattach
PORTVERSION=	1.0
CATEGORIES=	net

MAINTAINER=	franco@opnsense.org
COMMENT=	Netgraph(4) tool for per-device attach

USE_GITHUB=	yes
GH_ACCOUNT=	fichtner
GH_PROJECT=	ngattach

PLIST_FILES=    sbin/ngattach

.include <bsd.port.mk>
