#####################################
### Quirks for disabling features ###
#####################################

0ad_HARDENING_QUIRKS+=			nopie
R_HARDENING_QUIRKS+=			nopie norelro
acpi_call_HARDENING_QUIRKS+=		nopie norelro
adabooch_HARDENING_QUIRKS+=		nopie norelro
adacurses_HARDENING_QUIRKS+=		nopie
aespipe_HARDENING_QUIRKS+=		nopie
alliance_HARDENING_QUIRKS+=		nopie
amtc_HARDENING_QUIRKS+=			nopie
aoe_HARDENING_QUIRKS+=			nopie norelro
appleseed_HARDENING_QUIRKS+=		nopie
archivemount_HARDENING_QUIRKS+=		nopie norelro
arm-elf-binutils_HARDENING_QUIRKS+=	nopie norelro
arm-none-eabi-gcc492_HARDENING_QUIRKS+=	nopie norelro
atftp_HARDENING_QUIRKS+=		nopie norelro
ats_HARDENING_QUIRKS+=			nopie
auto-multiple-choice_HARDENING_QUIRKS+=	nopie
avidemux_HARDENING_QUIRKS+=		nopie norelro
babeld_HARDENING_QUIRKS+=		nopie
bashc_HARDENING_QUIRKS+=		nopie
beast_HARDENING_QUIRKS+=		nopie norelro
bibutils_HARDENING_QUIRKS+=		nopie
biosfont_HARDENING_QUIRKS+=		nopie norelro
bitcollider_HARDENING_QUIRKS+=		nopie
bmf_HARDENING_QUIRKS+=			nopie
bombono_HARDENING_QUIRKS+=		nopie norelro
braa_HARDENING_QUIRKS+=			nopie
braincurses_HARDENING_QUIRKS+=		nopie
bullet_HARDENING_QUIRKS+=		nopie
busybox_HARDENING_QUIRKS+=		nopie norelro
calculix_HARDENING_QUIRKS+=		nopie norelro
canna-lib_HARDENING_QUIRKS+=		nopie norelro
canna-server_HARDENING_QUIRKS+=		nopie norelro
caudium14_HARDENING_QUIRKS+=		norelro
ccons_HARDENING_QUIRKS+=		nopie norelro
cdf_HARDENING_QUIRKS+=			nopie
cdls_HARDENING_QUIRKS+=			nopie
cgnslib_HARDENING_QUIRKS+=		nopie
chkrootkit_HARDENING_QUIRKS+=		nopie norelro
chromium_HARDENING_QUIRKS+=		norelro
cimg_HARDENING_QUIRKS+=			nopie
clambc_HARDENING_QUIRKS+=		nopie norelro
clanlib22_HARDENING_QUIRKS+=		nopie norelro
cloudabi-utils_HARDENING_QUIRKS+=	nopie norelro
cmdwatch_HARDENING_QUIRKS+=		nopie
cmogstored_HARDENING_QUIRKS+=		nopie norelro
cmph_HARDENING_QUIRKS+=			nopie
condor_HARDENING_QUIRKS+=		nopie norelro
coreutils_HARDENING_QUIRKS+=		nopie norelro
courier-imap_HARDENING_QUIRKS+=		nopie norelro
crawl_HARDENING_QUIRKS+=		nopie
crf++_HARDENING_QUIRKS+=		nopie
criticalmass_HARDENING_QUIRKS+=		nopie norelro
csound6_HARDENING_QUIRKS+=		nopie norelro
cvc3_HARDENING_QUIRKS+=			nopie
cx88_HARDENING_QUIRKS+=			nopie norelro
cx_Freeze_HARDENING_QUIRKS+=		nopie norelro
cyrus-imapd25_HARDENING_QUIRKS+=	nopie
dahdi_HARDENING_QUIRKS+=		nopie norelro
dante_HARDENING_QUIRKS+=		nopie
darts_HARDENING_QUIRKS+=		nopie
dataplot_HARDENING_QUIRKS+=		nopie norelro
dbh_HARDENING_QUIRKS+=			nopie
deforaos-keyboard_HARDENING_QUIRKS+=	nopie
detachtty_HARDENING_QUIRKS+=		nopie
diamond_HARDENING_QUIRKS+=		nopie
dmucs_HARDENING_QUIRKS+=		nopie norelro
drawterm_HARDENING_QUIRKS+=		nopie
dsniff_HARDENING_QUIRKS+=		nopie
dtv_HARDENING_QUIRKS+=			nopie
dummyflash_HARDENING_QUIRKS+=		nopie norelro
dunelegacy_HARDENING_QUIRKS+=		nopie
dungeon_HARDENING_QUIRKS+=		nopie
dwarfdump_HARDENING_QUIRKS+=		nopie
dxirc_HARDENING_QUIRKS+=		nopie
dymo-cups-drivers_HARDENING_QUIRKS+=	nopie
e2fsprogs-libblkid_HARDENING_QUIRKS+=	norelro
e2fsprogs_HARDENING_QUIRKS+=		nopie
ebook2cw_HARDENING_QUIRKS+=		nopie
ebook2cwgui_HARDENING_QUIRKS+=		nopie
eif_HARDENING_QUIRKS+=			nopie
elfkickers_HARDENING_QUIRKS+=		nopie
elk_HARDENING_QUIRKS+=			nopie
emacs-devel_HARDENING_QUIRKS+=		nopie norelro
emacs_HARDENING_QUIRKS+=		nopie norelro
epiar_HARDENING_QUIRKS+=		nopie
fidogate_HARDENING_QUIRKS+=		nopie
firebird25-server_HARDENING_QUIRKS+=	nopie
firefox_HARDENING_QUIRKS+=		nopie
fl_moxgen_HARDENING_QUIRKS+=		nopie
flatzebra_HARDENING_QUIRKS+=		nopie norelro
fluxconf_HARDENING_QUIRKS+=		nopie norelro
fonulator_HARDENING_QUIRKS+=		nopie
forked-daapd_HARDENING_QUIRKS+=		nopie
fox17_HARDENING_QUIRKS+=		nopie
freebsd-tftp_HARDENING_QUIRKS+=		nopie
freevrrpd_HARDENING_QUIRKS+=		nopie
frobtads_HARDENING_QUIRKS+=		nopie
fs-uae_HARDENING_QUIRKS+=		nopie norelro
ftwin_HARDENING_QUIRKS+=		nopie
fusefs-ext4fuse_HARDENING_QUIRKS+=	nopie
fusefs-lkl_HARDENING_QUIRKS+=		nopie
fusefs-zip_HARDENING_QUIRKS+=		nopie
fwlogwatch_HARDENING_QUIRKS+=		nopie
gapcmon_HARDENING_QUIRKS+=		nopie
gatling_HARDENING_QUIRKS+=		nopie
gcc-arm-embedded_HARDENING_QUIRKS+=	nopie norelro
gcc46_HARDENING_QUIRKS+=		nopie norelro
gcc47_HARDENING_QUIRKS+=		nopie norelro
gcc48_HARDENING_QUIRKS+=		nopie norelro
gcc5-aux_HARDENING_QUIRKS+=		nopie norelro
gcc5-devel_HARDENING_QUIRKS+=		nopie norelro
gcc5_HARDENING_QUIRKS+=			nopie norelro
gcc6-aux_HARDENING_QUIRKS+=		nopie norelro
gcc6-devel_HARDENING_QUIRKS+=		nopie norelro
gcc6_HARDENING_QUIRKS+=			nopie norelro
gcc7-devel_HARDENING_QUIRKS+=		nopie norelro
gcompmgr_HARDENING_QUIRKS+=		nopie
gdk-pixbuf_HARDENING_QUIRKS+=		nopie norelro
getdp_HARDENING_QUIRKS+=		nopie
ghc_HARDENING_QUIRKS+=			nopie
gimp-app_HARDENING_QUIRKS+=		norelro
gle-graphics_HARDENING_QUIRKS+=		nopie
gltron_HARDENING_QUIRKS+=		nopie
gmerlin_HARDENING_QUIRKS+=		nopie norelro
gnomeattacks_HARDENING_QUIRKS+=		nopie
gnubg_HARDENING_QUIRKS+=		nopie norelro
gnustep-base_HARDENING_QUIRKS+=		nopie norelro
gprolog_HARDENING_QUIRKS+=		nopie
gracetmpl_HARDENING_QUIRKS+=		nopie norelro
graid5_HARDENING_QUIRKS+=		nopie norelro
graveman_HARDENING_QUIRKS+=		nopie
growl-for-linux_HARDENING_QUIRKS+=	nopie
grub2-efi_HARDENING_QUIRKS+=		nopie norelro
grub2-pcbsd_HARDENING_QUIRKS+=		nopie norelro
grub2_HARDENING_QUIRKS+=		nopie norelro
gtk-gnutella_HARDENING_QUIRKS+=		nopie norelro
gtkada3_HARDENING_QUIRKS+=		nopie norelro
gtkada_HARDENING_QUIRKS+=		nopie
gtkperf_HARDENING_QUIRKS+=		nopie
gtkradiant_HARDENING_QUIRKS+=		nopie
h2o_HARDENING_QUIRKS+=			nopie
h323plus_HARDENING_QUIRKS+=		nopie norelro
hadoop2_HARDENING_QUIRKS+=		nopie norelro
hadoop_HARDENING_QUIRKS+=		nopie norelro
hdf_HARDENING_QUIRKS+=			nopie norelro
heirloom-sh_HARDENING_QUIRKS+=		nopie
hhm_HARDENING_QUIRKS+=			nopie
honeyd_HARDENING_QUIRKS+=		nopie norelro
honggfuzz_HARDENING_QUIRKS+=		nopie
howl_HARDENING_QUIRKS+=			nopie
hs-X11_HARDENING_QUIRKS+=		nopie
hs-network_HARDENING_QUIRKS+=		nopie
hugs_HARDENING_QUIRKS+=			nopie norelro
icegenerator_HARDENING_QUIRKS+=		nopie norelro
iet_HARDENING_QUIRKS+=			nopie norelro
iffinder_HARDENING_QUIRKS+=		nopie
imagination_HARDENING_QUIRKS+=		nopie
imap-uw_HARDENING_QUIRKS+=		nopie
imapfilter_HARDENING_QUIRKS+=		nopie
ipsec-tools_HARDENING_QUIRKS+=		nopie norelro
iroffer-dinoex_HARDENING_QUIRKS+=	nopie norelro
isomd5sum_HARDENING_QUIRKS+=		nopie
jnettop_HARDENING_QUIRKS+=		nopie
jzip_HARDENING_QUIRKS+=			nopie
kbdscan_HARDENING_QUIRKS+=		nopie
kludge3d_HARDENING_QUIRKS+=		nopie norelro
kon2-16dot_HARDENING_QUIRKS+=		nopie
ksh93_HARDENING_QUIRKS+=		nopie norelro
kudu_HARDENING_QUIRKS+=			nopie
kvirc_HARDENING_QUIRKS+=		nopie
l4ip_HARDENING_QUIRKS+=			nopie
lapack_HARDENING_QUIRKS+=		nopie
lasso_HARDENING_QUIRKS+=		nopie norelro
lbreakout_HARDENING_QUIRKS+=		nopie
libmatheval_HARDENING_QUIRKS+=		nopie norelro
lisaem_HARDENING_QUIRKS+=		nopie
lmbench_HARDENING_QUIRKS+=		nopie
luajit_HARDENING_QUIRKS+=		nopie
madplay_HARDENING_QUIRKS+=		nopie
mafft_HARDENING_QUIRKS+=		nopie norelro
mame_HARDENING_QUIRKS+=			nopie norelro
mbdyn_HARDENING_QUIRKS+=		nopie
med_HARDENING_QUIRKS+=			nopie
mednafen_HARDENING_QUIRKS+=		nopie norelro
megaglest_HARDENING_QUIRKS+=		nopie
mess_HARDENING_QUIRKS+=			nopie
mftrace_HARDENING_QUIRKS+=		nopie norelro
mined_HARDENING_QUIRKS+=		nopie
mlan3_HARDENING_QUIRKS+=		nopie
mod_authn_otp_HARDENING_QUIRKS+=	nopie norelro
mongodb32-tools_HARDENING_QUIRKS+=	nopie norelro
mopac_HARDENING_QUIRKS+=		nopie
mp3guessenc_HARDENING_QUIRKS+=		nopie norelro
mph_HARDENING_QUIRKS+=			nopie
mpich2_HARDENING_QUIRKS+=		nopie norelro
mpqc_HARDENING_QUIRKS+=			nopie norelro
mpv_HARDENING_QUIRKS+=			nopie
msort_HARDENING_QUIRKS+=		nopie norelro
mtoolsfm_HARDENING_QUIRKS+=		nopie norelro
mumps_HARDENING_QUIRKS+=		nopie
mupen64plus-ui-console_HARDENING_QUIRKS+=nopie
muse_HARDENING_QUIRKS+=			nopie
musixtex_HARDENING_QUIRKS+=		nopie norelro
mysql57-server_HARDENING_QUIRKS+=	nopie norelro
ncbi-blast+_HARDENING_QUIRKS+=		nopie
ncp_HARDENING_QUIRKS+=			nopie
nefu_HARDENING_QUIRKS+=			nopie
netcdf-fortran_HARDENING_QUIRKS+=	nopie norelro
netmask_HARDENING_QUIRKS+=		nopie
netrik_HARDENING_QUIRKS+=		nopie
netustad_HARDENING_QUIRKS+=		nopie norelro
nfsshell_HARDENING_QUIRKS+=		nopie
ng_ipacct_HARDENING_QUIRKS+=		nopie norelro
ng_mikrotik_eoip_HARDENING_QUIRKS+=	nopie norelro
nn_HARDENING_QUIRKS+=			nopie
nokryptia_HARDENING_QUIRKS+=		nopie
nsca-ng_HARDENING_QUIRKS+=		nopie norelro
nss-pam-ldapd-sasl_HARDENING_QUIRKS+=	nopie norelro
nss-pam-ldapd_HARDENING_QUIRKS+=	nopie norelro
nut_HARDENING_QUIRKS+=			nopie norelro
nvclock_HARDENING_QUIRKS+=		nopie norelro
nvi-devel_HARDENING_QUIRKS+=		nopie
nvidia-driver_HARDENING_QUIRKS+=	nopie norelro
obpager_HARDENING_QUIRKS+=		nopie
octave_HARDENING_QUIRKS+=		nopie norelro
odt2txt_HARDENING_QUIRKS+=		nopie
opal_HARDENING_QUIRKS+=			nopie norelro
open-vm-tools_HARDENING_QUIRKS+=	nopie norelro
openbsc_HARDENING_QUIRKS+=		nopie norelro
openh323_HARDENING_QUIRKS+=		nopie norelro
openmpi_HARDENING_QUIRKS+=		nopie norelro
openomf_HARDENING_QUIRKS+=		nopie
opensips_HARDENING_QUIRKS+=		nopie norelro
opentracker_HARDENING_QUIRKS+=		nopie
openuniverse_HARDENING_QUIRKS+=		nopie
openvswitch_HARDENING_QUIRKS+=		nopie norelro
osquery_HARDENING_QUIRKS+=		nopie
oss_HARDENING_QUIRKS+=			nopie norelro
ossec-hids-server_HARDENING_QUIRKS+=	nopie
pacemaker_HARDENING_QUIRKS+=		nopie norelro
panda-imap_HARDENING_QUIRKS+=		nopie
parallels-tools_HARDENING_QUIRKS+=	nopie norelro
passivedns_HARDENING_QUIRKS+=		nopie
pcal_HARDENING_QUIRKS+=			nopie
pdftk_HARDENING_QUIRKS+=		nopie
pdnmesh_HARDENING_QUIRKS+=		nopie
pearpc_HARDENING_QUIRKS+=		nopie norelro
pgplot_HARDENING_QUIRKS+=		nopie
phat_HARDENING_QUIRKS+=			nopie
php56-extensions_HARDENING_QUIRKS+=	nopie norelro
php70-extensions_HARDENING_QUIRKS+=	nopie norelro
php71-extensions_HARDENING_QUIRKS+=	nopie norelro
phpmyadmin_HARDENING_QUIRKS+=		nopie norelro
pidgin-sipe_HARDENING_QUIRKS+=		nopie norelro
pim6-tools_HARDENING_QUIRKS+=		nopie
pinot_HARDENING_QUIRKS+=		nopie norelro
pioneer_HARDENING_QUIRKS+=		nopie norelro
pipenightdreams_HARDENING_QUIRKS+=	nopie
pnetcdf_HARDENING_QUIRKS+=		nopie norelro
pokerth_HARDENING_QUIRKS+=		nopie norelro
polyorb_HARDENING_QUIRKS+=		nopie norelro
portfwd_HARDENING_QUIRKS+=		nopie norelro
portmon_HARDENING_QUIRKS+=		nopie norelro
postgis22_HARDENING_QUIRKS+=		nopie norelro
povray37_HARDENING_QUIRKS+=		nopie
powerdns-recursor_HARDENING_QUIRKS+=	nopie
powerpc64-gcc_HARDENING_QUIRKS+=	nopie norelro
pprotectd_HARDENING_QUIRKS+=		nopie
primer3_HARDENING_QUIRKS+=		nopie
psi88_HARDENING_QUIRKS+=		nopie
pwlib_HARDENING_QUIRKS+=		nopie norelro
py-numpy_HARDENING_QUIRKS+=		nopie norelro
qd_HARDENING_QUIRKS+=			nopie norelro
qemu-cheri_HARDENING_QUIRKS+=		nopie norelro
qemu-devel_HARDENING_QUIRKS+=		nopie norelro
qemu-sbruno_HARDENING_QUIRKS+=		nopie norelro
qemu-user-static_HARDENING_QUIRKS+=	nopie norelro
qemu_HARDENING_QUIRKS+=			nopie norelro
quadra_HARDENING_QUIRKS+=		nopie
quakeforge_HARDENING_QUIRKS+=		nopie
racoon2_HARDENING_QUIRKS+=		nopie
rancid3_HARDENING_QUIRKS+=		nopie
rancid_HARDENING_QUIRKS+=		nopie
raop_play_HARDENING_QUIRKS+=		nopie
raster3d_HARDENING_QUIRKS+=		nopie norelro
rate_HARDENING_QUIRKS+=			nopie
razorback-api_HARDENING_QUIRKS+=	nopie norelro
rc_HARDENING_QUIRKS+=			nopie norelro
reduce_HARDENING_QUIRKS+=		nopie
rhtvision_HARDENING_QUIRKS+=		nopie
riak2_HARDENING_QUIRKS+=		nopie
rocksdb_HARDENING_QUIRKS+=		nopie
rodent_HARDENING_QUIRKS+=		nopie
rpc2_HARDENING_QUIRKS+=			nopie
rssh_HARDENING_QUIRKS+=			nopie
rubygem-passenger_HARDENING_QUIRKS+=	nopie norelro
rust-nightly_HARDENING_QUIRKS+=		nopie norelro
sam2p_HARDENING_QUIRKS+=		nopie norelro
sample_HARDENING_QUIRKS+=		nopie norelro
sbcl_HARDENING_QUIRKS+=			nopie
scanssh_HARDENING_QUIRKS+=		nopie norelro
scantailor_HARDENING_QUIRKS+=		nopie
scilab-toolbox-sivp_HARDENING_QUIRKS+=	nopie norelro
scilab-toolbox-swt_HARDENING_QUIRKS+=	nopie norelro
scribe_HARDENING_QUIRKS+=		nopie norelro
sdl2pp_HARDENING_QUIRKS+=		nopie
sdlCC_HARDENING_QUIRKS+=		nopie norelro
sdr-wspr_HARDENING_QUIRKS+=		nopie
seamonkey_HARDENING_QUIRKS+=		nopie norelro
send_HARDENING_QUIRKS+=			nopie norelro
sfft_HARDENING_QUIRKS+=			nopie
shaaft_HARDENING_QUIRKS+=		nopie norelro
shadowsocks-libev_HARDENING_QUIRKS+=	nopie
signing-party_HARDENING_QUIRKS+=	nopie
simdock_HARDENING_QUIRKS+=		nopie
skyeye_HARDENING_QUIRKS+=		nopie norelro
snoopy_HARDENING_QUIRKS+=		nopie norelro
spamdyke_HARDENING_QUIRKS+=		nopie norelro
spamprobe_HARDENING_QUIRKS+=		nopie norelro
spar_HARDENING_QUIRKS+=			nopie
spblas_HARDENING_QUIRKS+=		nopie
spidermonkey24_HARDENING_QUIRKS+=	nopie norelro
spread4_HARDENING_QUIRKS+=		nopie
spring_HARDENING_QUIRKS+=		nopie norelro
spybye_HARDENING_QUIRKS+=		nopie
squidpurge_HARDENING_QUIRKS+=		nopie
stegdetect_HARDENING_QUIRKS+=		nopie
superlu_mt_HARDENING_QUIRKS+=		nopie norelro
swi-pl_HARDENING_QUIRKS+=		nopie norelro
tarantool_HARDENING_QUIRKS+=		nopie
tayga_HARDENING_QUIRKS+=		nopie
tcc_HARDENING_QUIRKS+=			nopie norelro
tdom_HARDENING_QUIRKS+=			norelro
telegram-purple_HARDENING_QUIRKS+=	nopie norelro
tesla_HARDENING_QUIRKS+=		nopie norelro
texmacs_HARDENING_QUIRKS+=		nopie norelro
tiemu3_HARDENING_QUIRKS+=		nopie
tif22pnm_HARDENING_QUIRKS+=		nopie norelro
tinker_HARDENING_QUIRKS+=		nopie norelro
tinyldap_HARDENING_QUIRKS+=		nopie norelro
tleenx2_HARDENING_QUIRKS+=		nopie
tolua++_HARDENING_QUIRKS+=		nopie
tome4_HARDENING_QUIRKS+=		nopie
tracker_HARDENING_QUIRKS+=		nopie norelro
trafficserver_HARDENING_QUIRKS+=	nopie
tremulous_HARDENING_QUIRKS+=		nopie
trn_HARDENING_QUIRKS+=			nopie
truevision_HARDENING_QUIRKS+=		nopie norelro
tsito_HARDENING_QUIRKS+=		nopie
tvheadend_HARDENING_QUIRKS+=		nopie
u-boot-cubox-hummingboard_HARDENING_QUIRKS+=nopie norelro
u-boot-wandboard_HARDENING_QUIRKS+=	nopie norelro
uae_HARDENING_QUIRKS+=			nopie norelro
uartlirc_HARDENING_QUIRKS+=		nopie norelro
ucpp_HARDENING_QUIRKS+=			nopie
umodplayer_HARDENING_QUIRKS+=		nopie
uni2ascii_HARDENING_QUIRKS+=		nopie nopie
unquote_HARDENING_QUIRKS+=		nopie
unrar_HARDENING_QUIRKS+=		nopie
uplog_HARDENING_QUIRKS+=		nopie
upp_HARDENING_QUIRKS+=			nopie
urelay_HARDENING_QUIRKS+=		nopie
utftools_HARDENING_QUIRKS+=		nopie
valgrind-devel_HARDENING_QUIRKS+=	nopie norelro
valgrind_HARDENING_QUIRKS+=		nopie norelro
vdr_HARDENING_QUIRKS+=			nopie
vice_HARDENING_QUIRKS+=			nopie norelro
virtualbox-ose-additions_HARDENING_QUIRKS+=nopie norelro
vnc_HARDENING_QUIRKS+=			nopie norelro
vnless_HARDENING_QUIRKS+=		nopie
voipong_HARDENING_QUIRKS+=		nopie
vowpal_wabbit_HARDENING_QUIRKS+=	nopie norelro
waffle_HARDENING_QUIRKS+=		nopie
webstone-ssl_HARDENING_QUIRKS+=		nopie
webstone_HARDENING_QUIRKS+=		nopie norelro
wifimgr_HARDENING_QUIRKS+=		nopie
wipe_HARDENING_QUIRKS+=			nopie norelro
wizd_HARDENING_QUIRKS+=			nopie
wmblob_HARDENING_QUIRKS+=		nopie norelro
wmwifi_HARDENING_QUIRKS+=		nopie
wxgtk30_HARDENING_QUIRKS+=		nopie norelro
x12arima_HARDENING_QUIRKS+=		nopie norelro
x265_HARDENING_QUIRKS+=			nopie
xchat-fish_HARDENING_QUIRKS+=		nopie
xen-tools_HARDENING_QUIRKS+=		nopie norelro
xiphos_HARDENING_QUIRKS+=		nopie norelro
xlogical_HARDENING_QUIRKS+=		nopie
xlogmaster_HARDENING_QUIRKS+=		nopie norelro
xmms-gbsplay_HARDENING_QUIRKS+=		nopie norelro
xmms-nas_HARDENING_QUIRKS+=		nopie norelro
xorg-server_HARDENING_QUIRKS+=		norelro
xpacman_HARDENING_QUIRKS+=		nopie
xpaint_HARDENING_QUIRKS+=		nopie norelro
xpvm_HARDENING_QUIRKS+=			nopie
xrally_HARDENING_QUIRKS+=		nopie norelro
xymon-server_HARDENING_QUIRKS+=		nopie
yadifa_HARDENING_QUIRKS+=		nopie norelro
yap-devel_HARDENING_QUIRKS+=		nopie norelro
yap_HARDENING_QUIRKS+=			nopie norelro
yorick_HARDENING_QUIRKS+=		nopie
ytree_HARDENING_QUIRKS+=		nopie
zinnia_HARDENING_QUIRKS+=		nopie
zphoto_HARDENING_QUIRKS+=		nopie

####################################
### Quirks for enabling features ###
####################################

aircrack-ng_HARDENING_QUIRKS+=		safestack
amap_HARDENING_QUIRKS+=			safestack
apache24_HARDENING_QUIRKS+=		safestack
apinger_HARDENING_QUIRKS+=		safestack
arandr_HARDENING_QUIRKS+=		safestack
arp-scan_HARDENING_QUIRKS+=		safestack
baka-mplayer_HARDENING_QUIRKS+=		safestack
bash-completion_HARDENING_QUIRKS+=	safestack
bash_HARDENING_QUIRKS+=			safestack
beautifulsoup_HARDENING_QUIRKS+=	safestack
beautify_HARDENING_QUIRKS+=		safestack
beep_HARDENING_QUIRKS+=			safestack
bitlbee_HARDENING_QUIRKS+=		safestack
clamav_HARDENING_QUIRKS+=		safestack
clog_HARDENING_QUIRKS+=			safestack
cpustats_HARDENING_QUIRKS+=		safestack
ctags_HARDENING_QUIRKS+=		safestack
cups-pdf_HARDENING_QUIRKS+=		safestack
dhcpcd_HARDENING_QUIRKS+=		safestack
dhcpleases_HARDENING_QUIRKS+=		safestack
dmenu_HARDENING_QUIRKS+=		safestack
dnspython_HARDENING_QUIRKS+=		safestack
dnsrecon_HARDENING_QUIRKS+=		safestack
dnstracer_HARDENING_QUIRKS+=		safestack
doas_HARDENING_QUIRKS+=			safestack
dosunix_HARDENING_QUIRKS+=		safestack
dvd+rw-tools_HARDENING_QUIRKS+=		safestack
dvdauthor_HARDENING_QUIRKS+=		safestack
eog_HARDENING_QUIRKS+=			safestack
feh_HARDENING_QUIRKS+=			safestack
filterdns_HARDENING_QUIRKS+=		safestack
filterlog_HARDENING_QUIRKS+=		safestack
fluxbox_HARDENING_QUIRKS+=		safestack
focusblur_HARDENING_QUIRKS+=		safestack
foo2zjs_HARDENING_QUIRKS+=		safestack
foomatic-filters_HARDENING_QUIRKS+=	safestack
fpdns_HARDENING_QUIRKS+=		safestack
freerdp_HARDENING_QUIRKS+=		safestack
freetalk_HARDENING_QUIRKS+=		safestack
giblib_HARDENING_QUIRKS+=		safestack
gimp-lqr-plugin_HARDENING_QUIRKS+=	safestack
gimp-save-for-web_HARDENING_QUIRKS+=	safestack
gimp_HARDENING_QUIRKS+=			safestack
git_HARDENING_QUIRKS+=			safestack
gnupg_HARDENING_QUIRKS+=		safestack
graphviz_HARDENING_QUIRKS+=		safestack
gtk-theme-switch_HARDENING_QUIRKS+=	safestack
hcidump_HARDENING_QUIRKS+=		safestack
hexedit_HARDENING_QUIRKS+=		safestack
hping_HARDENING_QUIRKS+=		safestack
htop_HARDENING_QUIRKS+=			safestack
httptunnel_HARDENING_QUIRKS+=		safestack
i3_HARDENING_QUIRKS+=			safestack
i3lock_HARDENING_QUIRKS+=		safestack
ifinfo_HARDENING_QUIRKS+=		safestack
ipython_HARDENING_QUIRKS+=		safestack
irssi-otr_HARDENING_QUIRKS+=		safestack
irssi_HARDENING_QUIRKS+=		safestack
keepassx_HARDENING_QUIRKS+=		safestack
kismet_HARDENING_QUIRKS+=		safestack
lensfun_HARDENING_QUIRKS+=		safestack
libotr_HARDENING_QUIRKS+=		safestack
loudmouth_HARDENING_QUIRKS+=		safestack
lsof_HARDENING_QUIRKS+=			safestack
ltrace_HARDENING_QUIRKS+=		safestack
lynx_HARDENING_QUIRKS+=			safestack
lzma_HARDENING_QUIRKS+=			safestack
makepasswd_HARDENING_QUIRKS+=		safestack
mcabber_HARDENING_QUIRKS+=		safestack
memdump_HARDENING_QUIRKS+=		safestack
mpage_HARDENING_QUIRKS+=		safestack
mpc-qt_HARDENING_QUIRKS+=		safestack
mpv_HARDENING_QUIRKS+=			safestack
mtr_HARDENING_QUIRKS+=			safestack
mutt_HARDENING_QUIRKS+=			safestack
nano_HARDENING_QUIRKS+=			safestack
ncrack_HARDENING_QUIRKS+=		safestack
neomutt_HARDENING_QUIRKS+=		safestack
netaddr_HARDENING_QUIRKS+=		safestack
netcat_HARDENING_QUIRKS+=		safestack
netsed_HARDENING_QUIRKS+=		safestack
nfsshell_HARDENING_QUIRKS+=		safestack
ngircd_HARDENING_QUIRKS+=		safestack
ngrep_HARDENING_QUIRKS+=		safestack
nip2_HARDENING_QUIRKS+=			safestack
nmap_HARDENING_QUIRKS+=			safestack
ntfs_HARDENING_QUIRKS+=			safestack
ntp_HARDENING_QUIRKS+=			safestack
openntpd_HARDENING_QUIRKS+=		safestack
openvpn23_HARDENING_QUIRKS+=		safestack
openvpn_HARDENING_QUIRKS+=		safestack
opnsense-update_HARDENING_QUIRKS+=	safestack
otr_HARDENING_QUIRKS+=			safestack
patchage_HARDENING_QUIRKS+=		safestack
pciids_HARDENING_QUIRKS+=		safestack
pcmanfm_HARDENING_QUIRKS+=		safestack
pdfcrack_HARDENING_QUIRKS+=		safestack
pidgin_HARDENING_QUIRKS+=		safestack
pidof_HARDENING_QUIRKS+=		safestack
pkg_HARDENING_QUIRKS+=			safestack
pkg_cutleaves_HARDENING_QUIRKS+=	safestack
portupgrade_HARDENING_QUIRKS+=		safestack
proxychains-ng_HARDENING_QUIRKS+=	safestack
proxychains_HARDENING_QUIRKS+=		safestack
pv_HARDENING_QUIRKS+=			safestack
requests_HARDENING_QUIRKS+=		safestack
rsync_HARDENING_QUIRKS+=		safestack
rtorrent_HARDENING_QUIRKS+=		safestack
scons_HARDENING_QUIRKS+=		safestack
screen_HARDENING_QUIRKS+=		safestack
scrot_HARDENING_QUIRKS+=		safestack
separate_HARDENING_QUIRKS+=		safestack
snort_HARDENING_QUIRKS+=		safestack
socat_HARDENING_QUIRKS+=		safestack
sqlmap_HARDENING_QUIRKS+=		safestack
sshlockout_pf_HARDENING_QUIRKS+=	safestack
sslscan_HARDENING_QUIRKS+=		safestack
sslsniffer_HARDENING_QUIRKS+=		safestack
sslsplit_HARDENING_QUIRKS+=		safestack
ssmping_HARDENING_QUIRKS+=		safestack
stunnel_HARDENING_QUIRKS+=		safestack
suricata_HARDENING_QUIRKS+=		safestack
swig_HARDENING_QUIRKS+=			safestack
syslogd_HARDENING_QUIRKS+=		safestack
tar_HARDENING_QUIRKS+=			safestack
tcpdump_HARDENING_QUIRKS+=		safestack
tcptraceroute_HARDENING_QUIRKS+=	safestack
terminology_HARDENING_QUIRKS+=		safestack
tigervnc_HARDENING_QUIRKS+=		safestack
tmux_HARDENING_QUIRKS+=			safestack
tor_HARDENING_QUIRKS+=			safestack
tor_HARDENING_QUIRKS+=			safestack
torsocks_HARDENING_QUIRKS+=		safestack
transmission_HARDENING_QUIRKS+=		safestack
tree_HARDENING_QUIRKS+=			safestack
udptunnel_HARDENING_QUIRKS+=		safestack
unicornscan_HARDENING_QUIRKS+=		safestack
unix2dos_HARDENING_QUIRKS+=		safestack
unrar_HARDENING_QUIRKS+=		safestack
vim_HARDENING_QUIRKS+=			safestack
vinagre_HARDENING_QUIRKS+=		safestack
vlock_HARDENING_QUIRKS+=		safestack
vnccrack_HARDENING_QUIRKS+=		safestack
vpnc_HARDENING_QUIRKS+=			safestack
w3m_HARDENING_QUIRKS+=			safestack
wapiti_HARDENING_QUIRKS+=		safestack
wavelet-decompose_HARDENING_QUIRKS+=	safestack
wavelet-sharpen_HARDENING_QUIRKS+=	safestack
wayland_HARDENING_QUIRKS+=		safestack
weechat_HARDENING_QUIRKS+=		safestack
wget_HARDENING_QUIRKS+=			safestack
whatweb_HARDENING_QUIRKS+=		safestack
whois_HARDENING_QUIRKS+=		safestack
xchm_HARDENING_QUIRKS+=			safestack
xrandr_HARDENING_QUIRKS+=		safestack
xterm_HARDENING_QUIRKS+=		safestack
xtrlock_HARDENING_QUIRKS+=		safestack
yafic_HARDENING_QUIRKS+=		safestack
yersinia_HARDENING_QUIRKS+=		safestack
youtube_dl_HARDENING_QUIRKS+=		safestack
zsh_HARDENING_QUIRKS+=			safestack
