0ad_HARDENING_QURIKS+=			nopie
R_HARDENING_QURIKS+=			nopie norelro
acpi_call_HARDENING_QURIKS+=		nopie norelro
adabooch_HARDENING_QURIKS+=		nopie norelro
adacurses_HARDENING_QURIKS+=		nopie
aespipe_HARDENING_QURIKS+=		nopie
alliance_HARDENING_QURIKS+=		nopie
amtc_HARDENING_QURIKS+=			nopie
aoe_HARDENING_QURIKS+=			nopie norelro
appleseed_HARDENING_QURIKS+=		nopie
archivemount_HARDENING_QURIKS+=		nopie norelro
arm-elf-binutils_HARDENING_QURIKS+=	nopie norelro
arm-none-eabi-gcc492_HARDENING_QURIKS+=	nopie norelro
atftp_HARDENING_QURIKS+=		nopie norelro
ats_HARDENING_QURIKS+=			nopie
auto-multiple-choice_HARDENING_QURIKS+=	nopie
avidemux_HARDENING_QURIKS+=		nopie norelro
babeld_HARDENING_QURIKS+=		nopie
bashc_HARDENING_QURIKS+=		nopie
beast_HARDENING_QURIKS+=		nopie norelro
bibutils_HARDENING_QURIKS+=		nopie
biosfont_HARDENING_QURIKS+=		nopie norelro
bitcollider_HARDENING_QURIKS+=		nopie
bmf_HARDENING_QURIKS+=			nopie
bombono_HARDENING_QURIKS+=		nopie norelro
braa_HARDENING_QURIKS+=			nopie
braincurses_HARDENING_QURIKS+=		nopie
bullet_HARDENING_QURIKS+=		nopie
busybox_HARDENING_QURIKS+=		nopie norelro
calculix_HARDENING_QURIKS+=		nopie norelro
canna-lib_HARDENING_QURIKS+=		nopie norelro
canna-server_HARDENING_QURIKS+=		nopie norelro
caudium14_HARDENING_QURIKS+=		norelro
ccons_HARDENING_QURIKS+=		nopie norelro
cdf_HARDENING_QURIKS+=			nopie
cdls_HARDENING_QURIKS+=			nopie
cgnslib_HARDENING_QURIKS+=		nopie
chkrootkit_HARDENING_QURIKS+=		nopie norelro
chromium_HARDENING_QURIKS+=		norelro
cimg_HARDENING_QURIKS+=			nopie
clambc_HARDENING_QURIKS+=		nopie norelro
clanlib22_HARDENING_QURIKS+=		nopie norelro
cloudabi-utils_HARDENING_QURIKS+=	nopie norelro
cmdwatch_HARDENING_QURIKS+=		nopie
cmogstored_HARDENING_QURIKS+=		nopie norelro
cmph_HARDENING_QURIKS+=			nopie
condor_HARDENING_QURIKS+=		nopie norelro
coreutils_HARDENING_QURIKS+=		nopie norelro
courier-imap_HARDENING_QURIKS+=		nopie norelro
crawl_HARDENING_QURIKS+=		nopie
crf++_HARDENING_QURIKS+=		nopie
criticalmass_HARDENING_QURIKS+=		nopie norelro
csound6_HARDENING_QURIKS+=		nopie norelro
cvc3_HARDENING_QURIKS+=			nopie
cx88_HARDENING_QURIKS+=			nopie norelro
cx_Freeze_HARDENING_QURIKS+=		nopie norelro
cyrus-imapd25_HARDENING_QURIKS+=	nopie
dahdi_HARDENING_QURIKS+=		nopie norelro
dante_HARDENING_QURIKS+=		nopie
darts_HARDENING_QURIKS+=		nopie
dataplot_HARDENING_QURIKS+=		nopie norelro
dbh_HARDENING_QURIKS+=			nopie
deforaos-keyboard_HARDENING_QURIKS+=	nopie
detachtty_HARDENING_QURIKS+=		nopie
diamond_HARDENING_QURIKS+=		nopie
dmucs_HARDENING_QURIKS+=		nopie norelro
drawterm_HARDENING_QURIKS+=		nopie
dsniff_HARDENING_QURIKS+=		nopie
dtv_HARDENING_QURIKS+=			nopie
dummyflash_HARDENING_QURIKS+=		nopie norelro
dunelegacy_HARDENING_QURIKS+=		nopie
dungeon_HARDENING_QURIKS+=		nopie
dwarfdump_HARDENING_QURIKS+=		nopie
dxirc_HARDENING_QURIKS+=		nopie
dymo-cups-drivers_HARDENING_QURIKS+=	nopie
e2fsprogs-libblkid_HARDENING_QURIKS+=	norelro
e2fsprogs_HARDENING_QURIKS+=		nopie
ebook2cw_HARDENING_QURIKS+=		nopie
ebook2cwgui_HARDENING_QURIKS+=		nopie
eif_HARDENING_QURIKS+=			nopie
elfkickers_HARDENING_QURIKS+=		nopie
elk_HARDENING_QURIKS+=			nopie
emacs-devel_HARDENING_QURIKS+=		nopie norelro
emacs_HARDENING_QURIKS+=		nopie norelro
epiar_HARDENING_QURIKS+=		nopie
fidogate_HARDENING_QURIKS+=		nopie
firebird25-server_HARDENING_QURIKS+=	nopie
firefox_HARDENING_QURIKS+=		nopie
fl_moxgen_HARDENING_QURIKS+=		nopie
flatzebra_HARDENING_QURIKS+=		nopie norelro
fluxconf_HARDENING_QURIKS+=		nopie norelro
fonulator_HARDENING_QURIKS+=		nopie
forked-daapd_HARDENING_QURIKS+=		nopie
fox17_HARDENING_QURIKS+=		nopie
freebsd-tftp_HARDENING_QURIKS+=		nopie
freevrrpd_HARDENING_QURIKS+=		nopie
frobtads_HARDENING_QURIKS+=		nopie
fs-uae_HARDENING_QURIKS+=		nopie norelro
ftwin_HARDENING_QURIKS+=		nopie
fusefs-ext4fuse_HARDENING_QURIKS+=	nopie
fusefs-lkl_HARDENING_QURIKS+=		nopie
fusefs-zip_HARDENING_QURIKS+=		nopie
fwlogwatch_HARDENING_QURIKS+=		nopie
gapcmon_HARDENING_QURIKS+=		nopie
gatling_HARDENING_QURIKS+=		nopie
gcc-arm-embedded_HARDENING_QURIKS+=	nopie norelro
gcc46_HARDENING_QURIKS+=		nopie norelro
gcc47_HARDENING_QURIKS+=		nopie norelro
gcc48_HARDENING_QURIKS+=		nopie norelro
gcc5-aux_HARDENING_QURIKS+=		nopie norelro
gcc5-devel_HARDENING_QURIKS+=		nopie norelro
gcc5_HARDENING_QURIKS+=			nopie norelro
gcc6-aux_HARDENING_QURIKS+=		nopie norelro
gcc6-devel_HARDENING_QURIKS+=		nopie norelro
gcc6_HARDENING_QURIKS+=			nopie norelro
gcc7-devel_HARDENING_QURIKS+=		nopie norelro
gcompmgr_HARDENING_QURIKS+=		nopie
gdk-pixbuf_HARDENING_QURIKS+=		nopie norelro
getdp_HARDENING_QURIKS+=		nopie
ghc_HARDENING_QURIKS+=			nopie
gimp-app_HARDENING_QURIKS+=		norelro
gle-graphics_HARDENING_QURIKS+=		nopie
gltron_HARDENING_QURIKS+=		nopie
gmerlin_HARDENING_QURIKS+=		nopie norelro
gnomeattacks_HARDENING_QURIKS+=		nopie
gnubg_HARDENING_QURIKS+=		nopie norelro
gnustep-base_HARDENING_QURIKS+=		nopie norelro
gprolog_HARDENING_QURIKS+=		nopie
gracetmpl_HARDENING_QURIKS+=		nopie norelro
graid5_HARDENING_QURIKS+=		nopie norelro
graveman_HARDENING_QURIKS+=		nopie
growl-for-linux_HARDENING_QURIKS+=	nopie
grub2-efi_HARDENING_QURIKS+=		nopie norelro
grub2-pcbsd_HARDENING_QURIKS+=		nopie norelro
grub2_HARDENING_QURIKS+=		nopie norelro
gtk-gnutella_HARDENING_QURIKS+=		nopie norelro
gtkada3_HARDENING_QURIKS+=		nopie norelro
gtkada_HARDENING_QURIKS+=		nopie
gtkperf_HARDENING_QURIKS+=		nopie
gtkradiant_HARDENING_QURIKS+=		nopie
h2o_HARDENING_QURIKS+=			nopie
h323plus_HARDENING_QURIKS+=		nopie norelro
hadoop2_HARDENING_QURIKS+=		nopie norelro
hadoop_HARDENING_QURIKS+=		nopie norelro
hdf_HARDENING_QURIKS+=			nopie norelro
heirloom-sh_HARDENING_QURIKS+=		nopie
hhm_HARDENING_QURIKS+=			nopie
honeyd_HARDENING_QURIKS+=		nopie norelro
honggfuzz_HARDENING_QURIKS+=		nopie
howl_HARDENING_QURIKS+=			nopie
hs-X11_HARDENING_QURIKS+=		nopie
hs-network_HARDENING_QURIKS+=		nopie
hugs_HARDENING_QURIKS+=			nopie norelro
icegenerator_HARDENING_QURIKS+=		nopie norelro
iet_HARDENING_QURIKS+=			nopie norelro
iffinder_HARDENING_QURIKS+=		nopie
imagination_HARDENING_QURIKS+=		nopie
imap-uw_HARDENING_QURIKS+=		nopie
imapfilter_HARDENING_QURIKS+=		nopie
ipsec-tools_HARDENING_QURIKS+=		nopie norelro
iroffer-dinoex_HARDENING_QURIKS+=	nopie norelro
isomd5sum_HARDENING_QURIKS+=		nopie
jnettop_HARDENING_QURIKS+=		nopie
jzip_HARDENING_QURIKS+=			nopie
kbdscan_HARDENING_QURIKS+=		nopie
kludge3d_HARDENING_QURIKS+=		nopie norelro
kon2-16dot_HARDENING_QURIKS+=		nopie
ksh93_HARDENING_QURIKS+=		nopie norelro
kudu_HARDENING_QURIKS+=			nopie
kvirc_HARDENING_QURIKS+=		nopie
l4ip_HARDENING_QURIKS+=			nopie
lapack_HARDENING_QURIKS+=		nopie
lasso_HARDENING_QURIKS+=		nopie norelro
lbreakout_HARDENING_QURIKS+=		nopie
libmatheval_HARDENING_QURIKS+=		nopie norelro
lisaem_HARDENING_QURIKS+=		nopie
lmbench_HARDENING_QURIKS+=		nopie
luajit_HARDENING_QURIKS+=		nopie
madplay_HARDENING_QURIKS+=		nopie
mafft_HARDENING_QURIKS+=		nopie norelro
mame_HARDENING_QURIKS+=			nopie norelro
mbdyn_HARDENING_QURIKS+=		nopie
med_HARDENING_QURIKS+=			nopie
mednafen_HARDENING_QURIKS+=		nopie norelro
megaglest_HARDENING_QURIKS+=		nopie
mess_HARDENING_QURIKS+=			nopie
mftrace_HARDENING_QURIKS+=		nopie norelro
mined_HARDENING_QURIKS+=		nopie
mlan3_HARDENING_QURIKS+=		nopie
mod_authn_otp_HARDENING_QURIKS+=	nopie norelro
mongodb32-tools_HARDENING_QURIKS+=	nopie norelro
mopac_HARDENING_QURIKS+=		nopie
mp3guessenc_HARDENING_QURIKS+=		nopie norelro
mph_HARDENING_QURIKS+=			nopie
mpich2_HARDENING_QURIKS+=		nopie norelro
mpqc_HARDENING_QURIKS+=			nopie norelro
mpv_HARDENING_QURIKS+=			nopie
msort_HARDENING_QURIKS+=		nopie norelro
mtoolsfm_HARDENING_QURIKS+=		nopie norelro
mumps_HARDENING_QURIKS+=		nopie
mupen64plus-ui-console_HARDENING_QURIKS+=nopie
muse_HARDENING_QURIKS+=			nopie
musixtex_HARDENING_QURIKS+=		nopie norelro
mysql57-server_HARDENING_QURIKS+=	nopie norelro
ncbi-blast+_HARDENING_QURIKS+=		nopie
ncp_HARDENING_QURIKS+=			nopie
nefu_HARDENING_QURIKS+=			nopie
netcdf-fortran_HARDENING_QURIKS+=	nopie norelro
netmask_HARDENING_QURIKS+=		nopie
netrik_HARDENING_QURIKS+=		nopie
netustad_HARDENING_QURIKS+=		nopie norelro
nfsshell_HARDENING_QURIKS+=		nopie
ng_ipacct_HARDENING_QURIKS+=		nopie norelro
ng_mikrotik_eoip_HARDENING_QURIKS+=	nopie norelro
nn_HARDENING_QURIKS+=			nopie
nokryptia_HARDENING_QURIKS+=		nopie
nsca-ng_HARDENING_QURIKS+=		nopie norelro
nss-pam-ldapd-sasl_HARDENING_QURIKS+=	nopie norelro
nss-pam-ldapd_HARDENING_QURIKS+=	nopie norelro
nut_HARDENING_QURIKS+=			nopie norelro
nvclock_HARDENING_QURIKS+=		nopie norelro
nvi-devel_HARDENING_QURIKS+=		nopie
nvidia-driver_HARDENING_QURIKS+=	nopie norelro
obpager_HARDENING_QURIKS+=		nopie
octave_HARDENING_QURIKS+=		nopie norelro
odt2txt_HARDENING_QURIKS+=		nopie
opal_HARDENING_QURIKS+=			nopie norelro
open-vm-tools_HARDENING_QURIKS+=	nopie norelro
openbsc_HARDENING_QURIKS+=		nopie norelro
openh323_HARDENING_QURIKS+=		nopie norelro
openmpi_HARDENING_QURIKS+=		nopie norelro
openomf_HARDENING_QURIKS+=		nopie
opensips_HARDENING_QURIKS+=		nopie norelro
opentracker_HARDENING_QURIKS+=		nopie
openuniverse_HARDENING_QURIKS+=		nopie
openvswitch_HARDENING_QURIKS+=		nopie norelro
osquery_HARDENING_QURIKS+=		nopie
oss_HARDENING_QURIKS+=			nopie norelro
ossec-hids-server_HARDENING_QURIKS+=	nopie
pacemaker_HARDENING_QURIKS+=		nopie norelro
panda-imap_HARDENING_QURIKS+=		nopie
parallels-tools_HARDENING_QURIKS+=	nopie norelro
passivedns_HARDENING_QURIKS+=		nopie
pcal_HARDENING_QURIKS+=			nopie
pdftk_HARDENING_QURIKS+=		nopie
pdnmesh_HARDENING_QURIKS+=		nopie
pearpc_HARDENING_QURIKS+=		nopie norelro
pgplot_HARDENING_QURIKS+=		nopie
phat_HARDENING_QURIKS+=			nopie
php56-extensions_HARDENING_QURIKS+=	nopie norelro
php70-extensions_HARDENING_QURIKS+=	nopie norelro
php71-extensions_HARDENING_QURIKS+=	nopie norelro
phpmyadmin_HARDENING_QURIKS+=		nopie norelro
pidgin-sipe_HARDENING_QURIKS+=		nopie norelro
pim6-tools_HARDENING_QURIKS+=		nopie
pinot_HARDENING_QURIKS+=		nopie norelro
pioneer_HARDENING_QURIKS+=		nopie norelro
pipenightdreams_HARDENING_QURIKS+=	nopie
pnetcdf_HARDENING_QURIKS+=		nopie norelro
pokerth_HARDENING_QURIKS+=		nopie norelro
polyorb_HARDENING_QURIKS+=		nopie norelro
portfwd_HARDENING_QURIKS+=		nopie norelro
portmon_HARDENING_QURIKS+=		nopie norelro
postgis22_HARDENING_QURIKS+=		nopie norelro
povray37_HARDENING_QURIKS+=		nopie
powerdns-recursor_HARDENING_QURIKS+=	nopie
powerpc64-gcc_HARDENING_QURIKS+=	nopie norelro
pprotectd_HARDENING_QURIKS+=		nopie
primer3_HARDENING_QURIKS+=		nopie
psi88_HARDENING_QURIKS+=		nopie
pwlib_HARDENING_QURIKS+=		nopie norelro
py-numpy_HARDENING_QURIKS+=		nopie norelro
qd_HARDENING_QURIKS+=			nopie norelro
qemu-cheri_HARDENING_QURIKS+=		nopie norelro
qemu-devel_HARDENING_QURIKS+=		nopie norelro
qemu-sbruno_HARDENING_QURIKS+=		nopie norelro
qemu-user-static_HARDENING_QURIKS+=	nopie norelro
qemu_HARDENING_QURIKS+=			nopie norelro
quadra_HARDENING_QURIKS+=		nopie
quakeforge_HARDENING_QURIKS+=		nopie
racoon2_HARDENING_QURIKS+=		nopie
rancid3_HARDENING_QURIKS+=		nopie
rancid_HARDENING_QURIKS+=		nopie
raop_play_HARDENING_QURIKS+=		nopie
raster3d_HARDENING_QURIKS+=		nopie norelro
rate_HARDENING_QURIKS+=			nopie
razorback-api_HARDENING_QURIKS+=	nopie norelro
rc_HARDENING_QURIKS+=			nopie norelro
reduce_HARDENING_QURIKS+=		nopie
rhtvision_HARDENING_QURIKS+=		nopie
riak2_HARDENING_QURIKS+=		nopie
rocksdb_HARDENING_QURIKS+=		nopie
rodent_HARDENING_QURIKS+=		nopie
rpc2_HARDENING_QURIKS+=			nopie
rssh_HARDENING_QURIKS+=			nopie
rubygem-passenger_HARDENING_QURIKS+=	nopie norelro
rust-nightly_HARDENING_QURIKS+=		nopie norelro
sam2p_HARDENING_QURIKS+=		nopie norelro
sample_HARDENING_QURIKS+=		nopie norelro
sbcl_HARDENING_QURIKS+=			nopie
scanssh_HARDENING_QURIKS+=		nopie norelro
scantailor_HARDENING_QURIKS+=		nopie
scilab-toolbox-sivp_HARDENING_QURIKS+=	nopie norelro
scilab-toolbox-swt_HARDENING_QURIKS+=	nopie norelro
scribe_HARDENING_QURIKS+=		nopie norelro
sdl2pp_HARDENING_QURIKS+=		nopie
sdlCC_HARDENING_QURIKS+=		nopie norelro
sdr-wspr_HARDENING_QURIKS+=		nopie
seamonkey_HARDENING_QURIKS+=		nopie norelro
send_HARDENING_QURIKS+=			nopie norelro
sfft_HARDENING_QURIKS+=			nopie
shaaft_HARDENING_QURIKS+=		nopie norelro
shadowsocks-libev_HARDENING_QURIKS+=	nopie
signing-party_HARDENING_QURIKS+=	nopie
simdock_HARDENING_QURIKS+=		nopie
skyeye_HARDENING_QURIKS+=		nopie norelro
snoopy_HARDENING_QURIKS+=		nopie norelro
spamdyke_HARDENING_QURIKS+=		nopie norelro
spamprobe_HARDENING_QURIKS+=		nopie norelro
spar_HARDENING_QURIKS+=			nopie
spblas_HARDENING_QURIKS+=		nopie
spidermonkey24_HARDENING_QURIKS+=	nopie norelro
spread4_HARDENING_QURIKS+=		nopie
spring_HARDENING_QURIKS+=		nopie norelro
spybye_HARDENING_QURIKS+=		nopie
squidpurge_HARDENING_QURIKS+=		nopie
stegdetect_HARDENING_QURIKS+=		nopie
superlu_mt_HARDENING_QURIKS+=		nopie norelro
swi-pl_HARDENING_QURIKS+=		nopie norelro
tarantool_HARDENING_QURIKS+=		nopie
tayga_HARDENING_QURIKS+=		nopie
tcc_HARDENING_QURIKS+=			nopie norelro
tdom_HARDENING_QURIKS+=			norelro
telegram-purple_HARDENING_QURIKS+=	nopie norelro
tesla_HARDENING_QURIKS+=		nopie norelro
texmacs_HARDENING_QURIKS+=		nopie norelro
tiemu3_HARDENING_QURIKS+=		nopie
tif22pnm_HARDENING_QURIKS+=		nopie norelro
tinker_HARDENING_QURIKS+=		nopie norelro
tinyldap_HARDENING_QURIKS+=		nopie norelro
tleenx2_HARDENING_QURIKS+=		nopie
tolua++_HARDENING_QURIKS+=		nopie
tome4_HARDENING_QURIKS+=		nopie
tracker_HARDENING_QURIKS+=		nopie norelro
trafficserver_HARDENING_QURIKS+=	nopie
tremulous_HARDENING_QURIKS+=		nopie
trn_HARDENING_QURIKS+=			nopie
truevision_HARDENING_QURIKS+=		nopie norelro
tsito_HARDENING_QURIKS+=		nopie
tvheadend_HARDENING_QURIKS+=		nopie
u-boot-cubox-hummingboard_HARDENING_QURIKS+=nopie norelro
u-boot-wandboard_HARDENING_QURIKS+=	nopie norelro
uae_HARDENING_QURIKS+=			nopie norelro
uartlirc_HARDENING_QURIKS+=		nopie norelro
ucpp_HARDENING_QURIKS+=			nopie
umodplayer_HARDENING_QURIKS+=		nopie
uni2ascii_HARDENING_QURIKS+=		nopie nopie
unquote_HARDENING_QURIKS+=		nopie
unrar_HARDENING_QURIKS+=		nopie
uplog_HARDENING_QURIKS+=		nopie
upp_HARDENING_QURIKS+=			nopie
urelay_HARDENING_QURIKS+=		nopie
utftools_HARDENING_QURIKS+=		nopie
valgrind-devel_HARDENING_QURIKS+=	nopie norelro
valgrind_HARDENING_QURIKS+=		nopie norelro
vdr_HARDENING_QURIKS+=			nopie
vice_HARDENING_QURIKS+=			nopie norelro
virtualbox-ose-additions_HARDENING_QURIKS+=nopie norelro
vnc_HARDENING_QURIKS+=			nopie norelro
vnless_HARDENING_QURIKS+=		nopie
voipong_HARDENING_QURIKS+=		nopie
vowpal_wabbit_HARDENING_QURIKS+=	nopie norelro
waffle_HARDENING_QURIKS+=		nopie
webstone-ssl_HARDENING_QURIKS+=		nopie
webstone_HARDENING_QURIKS+=		nopie norelro
wifimgr_HARDENING_QURIKS+=		nopie
wipe_HARDENING_QURIKS+=			nopie norelro
wizd_HARDENING_QURIKS+=			nopie
wmblob_HARDENING_QURIKS+=		nopie norelro
wmwifi_HARDENING_QURIKS+=		nopie
wxgtk30_HARDENING_QURIKS+=		nopie norelro
x12arima_HARDENING_QURIKS+=		nopie norelro
x265_HARDENING_QURIKS+=			nopie
xchat-fish_HARDENING_QURIKS+=		nopie
xen-tools_HARDENING_QURIKS+=		nopie norelro
xiphos_HARDENING_QURIKS+=		nopie norelro
xlogical_HARDENING_QURIKS+=		nopie
xlogmaster_HARDENING_QURIKS+=		nopie norelro
xmms-gbsplay_HARDENING_QURIKS+=		nopie norelro
xmms-nas_HARDENING_QURIKS+=		nopie norelro
xorg-server_HARDENING_QURIKS+=		norelro
xpacman_HARDENING_QURIKS+=		nopie
xpaint_HARDENING_QURIKS+=		nopie norelro
xpvm_HARDENING_QURIKS+=			nopie
xrally_HARDENING_QURIKS+=		nopie norelro
xymon-server_HARDENING_QURIKS+=		nopie
yadifa_HARDENING_QURIKS+=		nopie norelro
yap-devel_HARDENING_QURIKS+=		nopie norelro
yap_HARDENING_QURIKS+=			nopie norelro
yorick_HARDENING_QURIKS+=		nopie
ytree_HARDENING_QURIKS+=		nopie
zinnia_HARDENING_QURIKS+=		nopie
zphoto_HARDENING_QURIKS+=		nopie
