#####################################
### Quirks for disabling features ###
#####################################

0ad_HARDENING+=				pie:off
R_HARDENING+=				pie:off relro:off
acpi_call_HARDENING+=			pie:off relro:off
adabooch_HARDENING+=			pie:off relro:off
adacurses_HARDENING+=			pie:off
aespipe_HARDENING+=			pie:off
alliance_HARDENING+=			pie:off
amtc_HARDENING+=			pie:off
aoe_HARDENING+=				pie:off relro:off
appleseed_HARDENING+=			pie:off
archivemount_HARDENING+=		pie:off relro:off
arm-elf-binutils_HARDENING+=		pie:off relro:off
arm-none-eabi-gcc492_HARDENING+=	pie:off relro:off
atftp_HARDENING+=			pie:off relro:off
ats_HARDENING+=				pie:off
auto-multiple-choice_HARDENING+=	pie:off
avidemux_HARDENING+=			pie:off relro:off
babeld_HARDENING+=			pie:off
bashc_HARDENING+=			pie:off
beast_HARDENING+=			pie:off relro:off
bibutils_HARDENING+=			pie:off
biosfont_HARDENING+=			pie:off relro:off
bitcollider_HARDENING+=			pie:off
bmf_HARDENING+=				pie:off
bombono_HARDENING+=			pie:off relro:off
braa_HARDENING+=			pie:off
braincurses_HARDENING+=			pie:off
bullet_HARDENING+=			pie:off
busybox_HARDENING+=			pie:off relro:off
calculix_HARDENING+=			pie:off relro:off
canna-lib_HARDENING+=			pie:off relro:off
canna-server_HARDENING+=		pie:off relro:off
caudium14_HARDENING+=			relro:off
ccons_HARDENING+=			pie:off relro:off
cdf_HARDENING+=				pie:off
cdls_HARDENING+=			pie:off
cgnslib_HARDENING+=			pie:off
chkrootkit_HARDENING+=			pie:off relro:off
chromium_HARDENING+=			relro:off
cimg_HARDENING+=			pie:off
clanlib22_HARDENING+=			pie:off relro:off
cloudabi-utils_HARDENING+=		pie:off relro:off
cmdwatch_HARDENING+=			pie:off
cmogstored_HARDENING+=			pie:off relro:off
cmph_HARDENING+=			pie:off
condor_HARDENING+=			pie:off relro:off
coreutils_HARDENING+=			pie:off relro:off
courier-imap_HARDENING+=		pie:off relro:off
crawl_HARDENING+=			pie:off
crf++_HARDENING+=			pie:off
criticalmass_HARDENING+=		pie:off relro:off
csound6_HARDENING+=			pie:off relro:off
cvc3_HARDENING+=			pie:off
cx88_HARDENING+=			pie:off relro:off
cx_Freeze_HARDENING+=			pie:off relro:off
cyrus-imapd25_HARDENING+=		pie:off
dahdi_HARDENING+=			pie:off relro:off
dante_HARDENING+=			pie:off
darts_HARDENING+=			pie:off
dataplot_HARDENING+=			pie:off relro:off
dbh_HARDENING+=				pie:off
deforaos-keyboard_HARDENING+=		pie:off
detachtty_HARDENING+=			pie:off
diamond_HARDENING+=			pie:off
dmucs_HARDENING+=			pie:off relro:off
drawterm_HARDENING+=			pie:off
dsniff_HARDENING+=			pie:off
dtv_HARDENING+=				pie:off
dummyflash_HARDENING+=			pie:off relro:off
dunelegacy_HARDENING+=			pie:off
dungeon_HARDENING+=			pie:off
dwarfdump_HARDENING+=			pie:off
dxirc_HARDENING+=			pie:off
dymo-cups-drivers_HARDENING+=		pie:off
e2fsprogs-libblkid_HARDENING+=		relro:off
e2fsprogs_HARDENING+=			pie:off
ebook2cw_HARDENING+=			pie:off
ebook2cwgui_HARDENING+=			pie:off
eif_HARDENING+=				pie:off
elfkickers_HARDENING+=			pie:off
elk_HARDENING+=				pie:off
emacs-devel_HARDENING+=			pie:off relro:off
emacs_HARDENING+=			pie:off relro:off
epiar_HARDENING+=			pie:off
fidogate_HARDENING+=			pie:off
firebird25-server_HARDENING+=		pie:off
firefox_HARDENING+=			pie:off
fl_moxgen_HARDENING+=			pie:off
flatzebra_HARDENING+=			pie:off relro:off
fluxconf_HARDENING+=			pie:off relro:off
fonulator_HARDENING+=			pie:off
forked-daapd_HARDENING+=		pie:off
fox17_HARDENING+=			pie:off
freebsd-tftp_HARDENING+=		pie:off
freevrrpd_HARDENING+=			pie:off
frobtads_HARDENING+=			pie:off
fs-uae_HARDENING+=			pie:off relro:off
ftwin_HARDENING+=			pie:off
fusefs-ext4fuse_HARDENING+=		pie:off
fusefs-lkl_HARDENING+=			pie:off
fusefs-zip_HARDENING+=			pie:off
fwlogwatch_HARDENING+=			pie:off
gapcmon_HARDENING+=			pie:off
gatling_HARDENING+=			pie:off
gcc-arm-embedded_HARDENING+=		pie:off relro:off
gcc46_HARDENING+=			pie:off relro:off
gcc47_HARDENING+=			pie:off relro:off
gcc48_HARDENING+=			pie:off relro:off
gcc5-aux_HARDENING+=			pie:off relro:off
gcc5-devel_HARDENING+=			pie:off relro:off
gcc5_HARDENING+=			pie:off relro:off
gcc6-aux_HARDENING+=			pie:off relro:off
gcc6-devel_HARDENING+=			pie:off relro:off
gcc6_HARDENING+=			pie:off relro:off
gcc7-devel_HARDENING+=			pie:off relro:off
gcompmgr_HARDENING+=			pie:off
gdk-pixbuf_HARDENING+=			pie:off relro:off
getdp_HARDENING+=			pie:off
ghc_HARDENING+=				pie:off
gimp-app_HARDENING+=			relro:off
gle-graphics_HARDENING+=		pie:off
gltron_HARDENING+=			pie:off
gmerlin_HARDENING+=			pie:off relro:off
gnomeattacks_HARDENING+=		pie:off
gnubg_HARDENING+=			pie:off relro:off
gnustep-base_HARDENING+=		pie:off relro:off
gprolog_HARDENING+=			pie:off
gracetmpl_HARDENING+=			pie:off relro:off
graid5_HARDENING+=			pie:off relro:off
graveman_HARDENING+=			pie:off
growl-for-linux_HARDENING+=		pie:off
grub2-efi_HARDENING+=			pie:off relro:off
grub2-pcbsd_HARDENING+=			pie:off relro:off
grub2_HARDENING+=			pie:off relro:off
gtk-gnutella_HARDENING+=		pie:off relro:off
gtkada3_HARDENING+=			pie:off relro:off
gtkada_HARDENING+=			pie:off
gtkperf_HARDENING+=			pie:off
gtkradiant_HARDENING+=			pie:off
h2o_HARDENING+=				pie:off
h323plus_HARDENING+=			pie:off relro:off
hadoop2_HARDENING+=			pie:off relro:off
hadoop_HARDENING+=			pie:off relro:off
hdf_HARDENING+=				pie:off relro:off
heirloom-sh_HARDENING+=			pie:off
hhm_HARDENING+=				pie:off
honeyd_HARDENING+=			pie:off relro:off
honggfuzz_HARDENING+=			pie:off
howl_HARDENING+=			pie:off
hs-X11_HARDENING+=			pie:off
hs-network_HARDENING+=			pie:off
hugs_HARDENING+=			pie:off relro:off
icegenerator_HARDENING+=		pie:off relro:off
iet_HARDENING+=				pie:off relro:off
iffinder_HARDENING+=			pie:off
imagination_HARDENING+=			pie:off
imap-uw_HARDENING+=			pie:off
imapfilter_HARDENING+=			pie:off
ipsec-tools_HARDENING+=			pie:off relro:off
iroffer-dinoex_HARDENING+=		pie:off relro:off
isomd5sum_HARDENING+=			pie:off
jnettop_HARDENING+=			pie:off
jzip_HARDENING+=			pie:off
kbdscan_HARDENING+=			pie:off
kludge3d_HARDENING+=			pie:off relro:off
kon2-16dot_HARDENING+=			pie:off
ksh93_HARDENING+=			pie:off relro:off
kudu_HARDENING+=			pie:off
kvirc_HARDENING+=			pie:off
l4ip_HARDENING+=			pie:off
lapack_HARDENING+=			pie:off
lasso_HARDENING+=			pie:off relro:off
lbreakout_HARDENING+=			pie:off
libmatheval_HARDENING+=			pie:off relro:off
lisaem_HARDENING+=			pie:off
lmbench_HARDENING+=			pie:off
luajit_HARDENING+=			pie:off
madplay_HARDENING+=			pie:off
mafft_HARDENING+=			pie:off relro:off
mame_HARDENING+=			pie:off relro:off
mbdyn_HARDENING+=			pie:off
med_HARDENING+=				pie:off
mednafen_HARDENING+=			pie:off relro:off
megaglest_HARDENING+=			pie:off
mess_HARDENING+=			pie:off
mftrace_HARDENING+=			pie:off relro:off
mined_HARDENING+=			pie:off
mlan3_HARDENING+=			pie:off
mod_authn_otp_HARDENING+=		pie:off relro:off
mongodb32-tools_HARDENING+=		pie:off relro:off
mopac_HARDENING+=			pie:off
mp3guessenc_HARDENING+=			pie:off relro:off
mph_HARDENING+=				pie:off
mpich2_HARDENING+=			pie:off relro:off
mpqc_HARDENING+=			pie:off relro:off
mpv_HARDENING+=				pie:off
msort_HARDENING+=			pie:off relro:off
mtoolsfm_HARDENING+=			pie:off relro:off
mumps_HARDENING+=			pie:off
mupen64plus-ui-console_HARDENING+=	pie:off
muse_HARDENING+=			pie:off
musixtex_HARDENING+=			pie:off relro:off
mysql57-server_HARDENING+=		pie:off relro:off
ncbi-blast+_HARDENING+=			pie:off
ncp_HARDENING+=				pie:off
nefu_HARDENING+=			pie:off
netcdf-fortran_HARDENING+=		pie:off relro:off
netmask_HARDENING+=			pie:off
netrik_HARDENING+=			pie:off
netustad_HARDENING+=			pie:off relro:off
nfsshell_HARDENING+=			pie:off
ng_ipacct_HARDENING+=			pie:off relro:off
ng_mikrotik_eoip_HARDENING+=		pie:off relro:off
nn_HARDENING+=				pie:off
nokryptia_HARDENING+=			pie:off
nsca-ng_HARDENING+=			pie:off relro:off
nss-pam-ldapd-sasl_HARDENING+=		pie:off relro:off
nss-pam-ldapd_HARDENING+=		pie:off relro:off
nut_HARDENING+=				pie:off relro:off
nvclock_HARDENING+=			pie:off relro:off
nvi-devel_HARDENING+=			pie:off
nvidia-driver_HARDENING+=		pie:off relro:off
obpager_HARDENING+=			pie:off
octave_HARDENING+=			pie:off relro:off
odt2txt_HARDENING+=			pie:off
opal_HARDENING+=			pie:off relro:off
open-vm-tools_HARDENING+=		pie:off relro:off
openbsc_HARDENING+=			pie:off relro:off
openh323_HARDENING+=			pie:off relro:off
openmpi_HARDENING+=			pie:off relro:off
openomf_HARDENING+=			pie:off
opensips_HARDENING+=			pie:off relro:off
opentracker_HARDENING+=			pie:off
openuniverse_HARDENING+=		pie:off
openvswitch_HARDENING+=			pie:off relro:off
osquery_HARDENING+=			pie:off
oss_HARDENING+=				pie:off relro:off
ossec-hids-server_HARDENING+=		pie:off
pacemaker_HARDENING+=			pie:off relro:off
panda-imap_HARDENING+=			pie:off
parallels-tools_HARDENING+=		pie:off relro:off
passivedns_HARDENING+=			pie:off
pcal_HARDENING+=			pie:off
pdftk_HARDENING+=			pie:off
pdnmesh_HARDENING+=			pie:off
pearpc_HARDENING+=			pie:off relro:off
pgplot_HARDENING+=			pie:off
phat_HARDENING+=			pie:off
php56-extensions_HARDENING+=		pie:off relro:off
php70-extensions_HARDENING+=		pie:off relro:off
php71-extensions_HARDENING+=		pie:off relro:off
phpmyadmin_HARDENING+=			pie:off relro:off
pidgin-sipe_HARDENING+=			pie:off relro:off
pim6-tools_HARDENING+=			pie:off
pinot_HARDENING+=			pie:off relro:off
pioneer_HARDENING+=			pie:off relro:off
pipenightdreams_HARDENING+=		pie:off
pnetcdf_HARDENING+=			pie:off relro:off
pokerth_HARDENING+=			pie:off relro:off
polyorb_HARDENING+=			pie:off relro:off
portfwd_HARDENING+=			pie:off relro:off
portmon_HARDENING+=			pie:off relro:off
postgis22_HARDENING+=			pie:off relro:off
povray37_HARDENING+=			pie:off
powerdns-recursor_HARDENING+=		pie:off
powerpc64-gcc_HARDENING+=		pie:off relro:off
pprotectd_HARDENING+=			pie:off
primer3_HARDENING+=			pie:off
psi88_HARDENING+=			pie:off
pwlib_HARDENING+=			pie:off relro:off
qd_HARDENING+=				pie:off relro:off
qemu-cheri_HARDENING+=			pie:off relro:off
qemu-devel_HARDENING+=			pie:off relro:off
qemu-sbruno_HARDENING+=			pie:off relro:off
qemu-user-static_HARDENING+=		pie:off relro:off
qemu_HARDENING+=			pie:off relro:off
quadra_HARDENING+=			pie:off
quakeforge_HARDENING+=			pie:off
racoon2_HARDENING+=			pie:off
rancid3_HARDENING+=			pie:off
rancid_HARDENING+=			pie:off
raop_play_HARDENING+=			pie:off
raster3d_HARDENING+=			pie:off relro:off
rate_HARDENING+=			pie:off
razorback-api_HARDENING+=		pie:off relro:off
rc_HARDENING+=				pie:off relro:off
reduce_HARDENING+=			pie:off
rhtvision_HARDENING+=			pie:off
riak2_HARDENING+=			pie:off
rocksdb_HARDENING+=			pie:off
rodent_HARDENING+=			pie:off
rpc2_HARDENING+=			pie:off
rssh_HARDENING+=			pie:off
rubygem-passenger_HARDENING+=		pie:off relro:off
rust-nightly_HARDENING+=		pie:off relro:off
sam2p_HARDENING+=			pie:off relro:off
sample_HARDENING+=			pie:off relro:off
sbcl_HARDENING+=			pie:off
scanssh_HARDENING+=			pie:off relro:off
scantailor_HARDENING+=			pie:off
scilab-toolbox-sivp_HARDENING+=		pie:off relro:off
scilab-toolbox-swt_HARDENING+=		pie:off relro:off
scribe_HARDENING+=			pie:off relro:off
sdl2pp_HARDENING+=			pie:off
sdlCC_HARDENING+=			pie:off relro:off
sdr-wspr_HARDENING+=			pie:off
seamonkey_HARDENING+=			pie:off relro:off
send_HARDENING+=			pie:off relro:off
sfft_HARDENING+=			pie:off
shaaft_HARDENING+=			pie:off relro:off
shadowsocks-libev_HARDENING+=		pie:off
signing-party_HARDENING+=		pie:off
simdock_HARDENING+=			pie:off
skyeye_HARDENING+=			pie:off relro:off
snoopy_HARDENING+=			pie:off relro:off
spamdyke_HARDENING+=			pie:off relro:off
spamprobe_HARDENING+=			pie:off relro:off
spar_HARDENING+=			pie:off
spblas_HARDENING+=			pie:off
spidermonkey24_HARDENING+=		pie:off relro:off
spread4_HARDENING+=			pie:off
spring_HARDENING+=			pie:off relro:off
spybye_HARDENING+=			pie:off
squidpurge_HARDENING+=			pie:off
stegdetect_HARDENING+=			pie:off
superlu_mt_HARDENING+=			pie:off relro:off
swi-pl_HARDENING+=			pie:off relro:off
tarantool_HARDENING+=			pie:off
tcc_HARDENING+=				pie:off relro:off
tdom_HARDENING+=			relro:off
telegram-purple_HARDENING+=		pie:off relro:off
tesla_HARDENING+=			pie:off relro:off
texmacs_HARDENING+=			pie:off relro:off
tiemu3_HARDENING+=			pie:off
tif22pnm_HARDENING+=			pie:off relro:off
tinker_HARDENING+=			pie:off relro:off
tinyldap_HARDENING+=			pie:off relro:off
tleenx2_HARDENING+=			pie:off
tolua++_HARDENING+=			pie:off
tome4_HARDENING+=			pie:off
tracker_HARDENING+=			pie:off relro:off
trafficserver_HARDENING+=		pie:off
tremulous_HARDENING+=			pie:off
trn_HARDENING+=				pie:off
truevision_HARDENING+=			pie:off relro:off
tsito_HARDENING+=			pie:off
tvheadend_HARDENING+=			pie:off
u-boot-cubox-hummingboard_HARDENING+=	pie:off relro:off
u-boot-wandboard_HARDENING+=		pie:off relro:off
uae_HARDENING+=				pie:off relro:off
uartlirc_HARDENING+=			pie:off relro:off
ucpp_HARDENING+=			pie:off
umodplayer_HARDENING+=			pie:off
uni2ascii_HARDENING+=			pie:off pie:off
unquote_HARDENING+=			pie:off
unrar_HARDENING+=			pie:off
uplog_HARDENING+=			pie:off
upp_HARDENING+=				pie:off
urelay_HARDENING+=			pie:off
utftools_HARDENING+=			pie:off
valgrind-devel_HARDENING+=		pie:off relro:off
valgrind_HARDENING+=			pie:off relro:off
vdr_HARDENING+=				pie:off
vice_HARDENING+=			pie:off relro:off
virtualbox-ose-additions_HARDENING+=	pie:off relro:off
vnc_HARDENING+=				pie:off relro:off
vnless_HARDENING+=			pie:off
voipong_HARDENING+=			pie:off
vowpal_wabbit_HARDENING+=		pie:off relro:off
waffle_HARDENING+=			pie:off
webstone-ssl_HARDENING+=		pie:off
webstone_HARDENING+=			pie:off relro:off
wifimgr_HARDENING+=			pie:off
wipe_HARDENING+=			pie:off relro:off
wizd_HARDENING+=			pie:off
wmblob_HARDENING+=			pie:off relro:off
wmwifi_HARDENING+=			pie:off
wxgtk30_HARDENING+=			pie:off relro:off
x12arima_HARDENING+=			pie:off relro:off
x265_HARDENING+=			pie:off
xchat-fish_HARDENING+=			pie:off
xen-tools_HARDENING+=			pie:off relro:off
xiphos_HARDENING+=			pie:off relro:off
xlogical_HARDENING+=			pie:off
xlogmaster_HARDENING+=			pie:off relro:off
xmms-gbsplay_HARDENING+=		pie:off relro:off
xmms-nas_HARDENING+=			pie:off relro:off
xorg-server_HARDENING+=			relro:off
xpacman_HARDENING+=			pie:off
xpaint_HARDENING+=			pie:off relro:off
xpvm_HARDENING+=			pie:off
xrally_HARDENING+=			pie:off relro:off
xymon-server_HARDENING+=		pie:off
yadifa_HARDENING+=			pie:off relro:off
yap-devel_HARDENING+=			pie:off relro:off
yap_HARDENING+=				pie:off relro:off
yorick_HARDENING+=			pie:off
ytree_HARDENING+=			pie:off
zinnia_HARDENING+=			pie:off
zphoto_HARDENING+=			pie:off

####################################
### Quirks for enabling features ###
####################################

acme-client_HARDENING+=			safestack
aiccu_HARDENING+=			safestack
aircrack-ng_HARDENING+=			safestack
amap_HARDENING+=			safestack
apache24_HARDENING+=			safestack
apcupsd_HARDENING+=			safestack
arandr_HARDENING+=			safestack
automake_HARDENING+=			safestack
baka-mplayer_HARDENING+=		safestack
bandwidthd_HARDENING+=			safestack
bash-completion_HARDENING+=		safestack
bash_HARDENING+=			safestack
beautifulsoup_HARDENING+=		safestack
beautify_HARDENING+=			safestack
bind_HARDENING+=			safestack
bison_HARDENING+=			safestack
bitlbee_HARDENING+=			safestack
bsnmp-regex_HARDENING+=			safestack
bsnmp-ucd_HARDENING+=			safestack
cciss_vol_status_HARDENING+=		safestack
choparp_HARDENING+=			safestack
collectd_HARDENING+=			safestack
ctags_HARDENING+=			safestack
cups-pdf_HARDENING+=			safestack
darkstat_HARDENING+=			safestack
ddclient_HARDENING+=			safestack
dhcp6_HARDENING+=			safestack
dhcp_HARDENING+=			safestack
dhcpcd_HARDENING+=			safestack
dmenu_HARDENING+=			safestack
dmidecode_HARDENING+=			safestack
dnscrypt-proxy_HARDENING+=		safestack
dnsmasq_HARDENING+=			safestack
dnspython_HARDENING+=			safestack
dnsrecon_HARDENING+=			safestack
dnstracer_HARDENING+=			safestack
doas_HARDENING+=			safestack
dosunix_HARDENING+=			safestack
dvd+rw-tools_HARDENING+=		safestack
dvdauthor_HARDENING+=			safestack
eog_HARDENING+=				safestack
expiretable_HARDENING+=			safestack
feh_HARDENING+=				safestack
flashrom_HARDENING+=			safestack
flock_HARDENING+=			safestack
fluxbox_HARDENING+=			safestack
focusblur_HARDENING+=			safestack
foo2zjs_HARDENING+=			safestack
foomatic-filters_HARDENING+=		safestack
fpdns_HARDENING+=			safestack
freeradius_HARDENING+=			safestack
freerdp_HARDENING+=			safestack
freetalk_HARDENING+=			safestack
giblib_HARDENING+=			safestack
gimp-lqr-plugin_HARDENING+=		safestack
gimp-save-for-web_HARDENING+=		safestack
gimp_HARDENING+=			safestack
gmake_HARDENING+=			safestack
gnokii_HARDENING+=			safestack
gnupg_HARDENING+=			safestack
graphviz_HARDENING+=			safestack
gtk-theme-switch_HARDENING+=		safestack
hcidump_HARDENING+=			safestack
help2man_HARDENING+=			safestack
hexedit_HARDENING+=			safestack
hping_HARDENING+=			safestack
htop_HARDENING+=			safestack
httptunnel_HARDENING+=			safestack
i3_HARDENING+=				safestack
i3lock_HARDENING+=			safestack
iftop_HARDENING+=			safestack
igmpproxy_HARDENING+=			safestack
iperf_HARDENING+=			safestack
ipmitool_HARDENING+=			safestack
ipython_HARDENING+=			safestack
irssi-otr_HARDENING+=			safestack
irssi_HARDENING+=			safestack
joe_HARDENING+=				safestack
keepassx_HARDENING+=			safestack
kismet_HARDENING+=			safestack
lcdproc_HARDENING+=			safestack
lensfun_HARDENING+=			safestack
libotr_HARDENING+=			safestack
lightsquid_HARDENING+=			safestack
lldpd_HARDENING+=			safestack
loudmouth_HARDENING+=			safestack
lsof_HARDENING+=			safestack
ltrace_HARDENING+=			safestack
lynx_HARDENING+=			safestack
lzma_HARDENING+=			safestack
makepasswd_HARDENING+=			safestack
mc-light_HARDENING+=			safestack
mcabber_HARDENING+=			safestack
mdns-repeater_HARDENING+=		safestack
memdump_HARDENING+=			safestack
mk-livestatus_HARDENING+=		safestack
monit_HARDENING+=			safestack
mosquitto_HARDENING+=			safestack
mpage_HARDENING+=			safestack
mpc-qt_HARDENING+=			safestack
mpd_HARDENING+=				safestack
mpv_HARDENING+=				safestack
mtr_HARDENING+=				safestack
mutt_HARDENING+=			safestack
nano_HARDENING+=			safestack
ncrack_HARDENING+=			safestack
neomutt_HARDENING+=			safestack
netcat_HARDENING+=			safestack
netsed_HARDENING+=			safestack
nfsshell_HARDENING+=			safestack
ngircd_HARDENING+=			safestack
ngrep_HARDENING+=			safestack
nip2_HARDENING+=			safestack
nmap_HARDENING+=			safestack
nrpe_HARDENING+=			safestack
ntfs_HARDENING+=			safestack
ntp_HARDENING+=				safestack
openconnect_HARDENING+=			safestack
openntpd_HARDENING+=			safestack
opensmtpd_HARDENING+=			safestack
openssh_HARDENING+=			safestack
otr_HARDENING+=				safestack
patch_HARDENING+=			safestack
patchage_HARDENING+=			safestack
pciids_HARDENING+=			safestack
pcmanfm_HARDENING+=			safestack
pdfcrack_HARDENING+=			safestack
pftop_HARDENING+=			safestack
pidgin_HARDENING+=			safestack
pidof_HARDENING+=			safestack
polipo_HARDENING+=			safestack
portupgrade_HARDENING+=			safestack
privoxy_HARDENING+=			safestack
proxy-suite_HARDENING+=			safestack
proxychains-ng_HARDENING+=		safestack
proxychains_HARDENING+=			safestack
pv_HARDENING+=				safestack
quagga_HARDENING+=			safestack
radvd_HARDENING+=			safestack
relayd_HARDENING+=			safestack
rrdtool_HARDENING+=			safestack
rsync_HARDENING+=			safestack
rtorrent_HARDENING+=			safestack
samplicator_HARDENING+=			safestack
sarg_HARDENING+=			safestack
scons_HARDENING+=			safestack
screen_HARDENING+=			safestack
scrot_HARDENING+=			safestack
separate_HARDENING+=			safestack
siproxd_HARDENING+=			safestack
smartmontools_HARDENING+=		safestack
smtp_HARDENING+=			safestack
snort_HARDENING+=			safestack
socat_HARDENING+=			safestack
softether_HARDENING+=			safestack
softether-devel_HARDENING+=		safestack
sqlmap_HARDENING+=			safestack
squid_HARDENING+=			safestack
sslh_HARDENING+=			safestack
sslscan_HARDENING+=			safestack
sslsniffer_HARDENING+=			safestack
sslsplit_HARDENING+=			safestack
ssmping_HARDENING+=			safestack
strongswan_HARDENING+=			safestack
stunnel_HARDENING+=			safestack
swig_HARDENING+=			safestack
sysinfo_HARDENING+=			safestack
tar_HARDENING+=				safestack
tarsnap_HARDENING+=			safestack
tcpdump_HARDENING+=			safestack
tcptraceroute_HARDENING+=		safestack
terminology_HARDENING+=			safestack
texinfo_HARDENING+=			safestack
tigervnc_HARDENING+=			safestack
tinc_HARDENING+=			safestack
tinyproxy_HARDENING+=			safestack
tmux_HARDENING+=			safestack
tor_HARDENING+=				safestack
torsocks_HARDENING+=			safestack
transmission_HARDENING+=		safestack
tree_HARDENING+=			safestack
udptunnel_HARDENING+=			safestack
uftp_HARDENING+=			safestack
unbound_HARDENING+=			safestack
unicornscan_HARDENING+=			safestack
unix2dos_HARDENING+=			safestack
unrar_HARDENING+=			safestack
usb_modeswitch_HARDENING+=		safestack
vim_HARDENING+=				safestack
vinagre_HARDENING+=			safestack
vlock_HARDENING+=			safestack
vnccrack_HARDENING+=			safestack
vnstat_HARDENING+=			safestack
vpnc_HARDENING+=			safestack
w3m_HARDENING+=				safestack
wapiti_HARDENING+=			safestack
watch_HARDENING+=			safestack
wavelet-decompose_HARDENING+=		safestack
wavelet-sharpen_HARDENING+=		safestack
wayland_HARDENING+=			safestack
webgrind_HARDENING+=			safestack
weechat_HARDENING+=			safestack
wget_HARDENING+=			safestack
whatweb_HARDENING+=			safestack
whois_HARDENING+=			safestack
wol_HARDENING+=				safestack
xchm_HARDENING+=			safestack
xrandr_HARDENING+=			safestack
xterm_HARDENING+=			safestack
xtrlock_HARDENING+=			safestack
yaf_HARDENING+=				safestack
yafic_HARDENING+=			safestack
yersinia_HARDENING+=			safestack
youtube_dl_HARDENING+=			safestack
