PORTNAME=	termstyle
DISTVERSION=	0.1.11
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	bofh@FreeBSD.org
COMMENT=	Dirt-simple terminal-colour library for python
WWW=		https://github.com/gfxmonk/termstyle

LICENSE=	BSD3CLAUSE

DEPRECATED=		Upstream project appears to be abandoned
EXPIRATION_DATE=	2026-05-08

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
