# Make all platforms(/engines(/frameworks.))
# $Id: Makefile,v 1.8 2005/08/29 20:41:52 cpressey Exp $

BASE=..
include $(BASE)/Config

all:
	(cd lua && ${MAKE} all)

clean:
	(cd lua && ${MAKE} clean)

distribution:
	(cd lua && ${MAKE} distribution)
