CARGO_CRATES=	heck-0.5.0 \
		libc-0.2.186 \
		once_cell-1.21.4 \
		portable-atomic-1.13.1 \
		proc-macro2-1.0.106 \
		pyo3-0.29.0 \
		pyo3-build-config-0.29.0 \
		pyo3-ffi-0.29.0 \
		pyo3-macros-0.29.0 \
		pyo3-macros-backend-0.29.0 \
		quote-1.0.45 \
		syn-2.0.117 \
		target-lexicon-0.13.5 \
		unicode-ident-1.0.24
