# Created by: Alonso Cardenas Marquez <acm@FreeBSD.org>
# $FreeBSD$

PORTREVISION=	0
PKGNAMESUFFIX=	-ui-console

COMMENT=	UI for Mupen64plus

MASTERDIR=	${.CURDIR}/../mupen64plus-core

USE_HARDENING=	pie:off

OPTIONS_DEFINE=	#

.include "${MASTERDIR}/Makefile"
