PORTNAME=	pysubs2
DISTVERSION=	1.9.0
CATEGORIES=	multimedia python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Library for editing subtitle files
WWW=		https://github.com/tkarabela/pysubs2

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

BUILD_DEPENDS=	${PYTHON_PKGNAMEPREFIX}hatchling>0:devel/py-hatchling@${PY_FLAVOR}

USES=		python
USE_PYTHON=	pep517 autoplist pytest

TEST_ENV=	${MAKE_ENV} PYTHONPATH=${STAGEDIR}${PYTHONPREFIX_SITELIBDIR}

BINARY_ALIAS=	python=${PYTHON_CMD} # only for tests

NO_ARCH=	yes

TEST_ARGS=	--disable-plugin-autoload

# tests as of 1.9.0: 144 passed, 3 warnings in 0.32s

.include <bsd.port.mk>
