# $FreeBSD$

PORTNAME=	network
PORTVERSION=   2.8.0.1
CATEGORIES=	net haskell

MAINTAINER=	haskell@FreeBSD.org
COMMENT=	Low-level networking interface

LICENSE=	BSD3CLAUSE

USE_HARDENING=	pie:off

IGNORE=		Haskell libraries are getting pushed out of the ports tree.

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
