--- pyproject.toml.orig	2026-04-06 20:40:36 UTC
+++ pyproject.toml
@@ -1,12 +1,9 @@ requires = [
 [build-system]
 # Should be mirrored in requirements/build.txt
 requires = [
-    "cmake>=3.26.1",
-    "ninja",
     "packaging>=24.2",
-    "setuptools>=77.0.3,<81.0.0",
+    "setuptools>=63.0",
     "setuptools-scm>=8.0",
-    "torch == 2.10.0",
     "wheel",
     "jinja2",
 ]
@@ -15,8 +12,7 @@ authors = [{name = "vLLM Team"}]
 [project]
 name = "vllm"
 authors = [{name = "vLLM Team"}]
-license = "Apache-2.0"
-license-files = ["LICENSE"]
+license = {text = "Apache-2.0"}
 readme = "README.md"
 description = "A high-throughput and memory-efficient inference and serving engine for LLMs"
 classifiers = [
