PORTNAME=	ports-tools
DISTVERSION=	1.10
CATEGORIES=	ports-mgmt

MAINTAINER=	pawelbsd@murena.io
COMMENT=	Collection of ports tree related scripts
WWW=		https://github.com/ppekala/ports-tools

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	ppekala

CONFLICTS_INSTALL=	popular # bin/pcheck

NO_ARCH=	yes
NO_BUILD=	yes

.include <bsd.port.mk>
