PORTNAME=	retriable
PORTVERSION=	3.4.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple DSL to retry failed code blocks
WWW=		https://github.com/kamui/retriable

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
