DISTVERSION?=	580.82.07
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	1

MASTERDIR=	${.CURDIR}/../nvidia-driver
PKGNAMESUFFIX=	-devel

.include "${MASTERDIR}/Makefile"
