PORTNAME=	RUnit
DISTVERSION=	0.4.33.1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R functions implementing a Unit Testing framework
WWW=		https://cran.r-project.org/package=RUnit

LICENSE=	GPLv2

USES=		cran

.include <bsd.port.mk>
