PORTNAME=	lang
PORTVERSION=	23.7.4
CATEGORIES=	sysutils
PKGNAMEPREFIX=	${GH_ACCOUNT}-

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense translations
WWW=		https://translate.opnsense.org/

LICENSE=	BSD2CLAUSE

USES=		gettext-tools

NO_ARCH=	yes
NO_BUILD=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	${CATEGORIES:[1]}

.include <bsd.port.mk>
