PORTNAME=	sshlockout_pf
PORTVERSION=	0.0.2
PORTREVISION=	2
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	Automatically block IPs with failed SSH logins using pf(4)

LICENSE=	BSD2CLAUSE

USE_HARDENING=	safestack

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense

PLIST_FILES=    sbin/sshlockout_pf

.include <bsd.port.mk>
