PORTNAME=	opnsense-installer
PORTVERSION=	21.7.1
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense installer scripts

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	cpdup:sysutils/cpdup
PREFIX=		/usr

NO_ARCH=	yes
NO_BUILD=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_PROJECT=	installer

.include <bsd.port.mk>
