PORTNAME=	opnsense-installer
PORTVERSION=	0.9
#PORTREVISION=	1 # GH_TAGNAME
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense installer scripts

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	cpdup:sysutils/cpdup
PREFIX=		/usr

NO_ARCH=	yes
NO_BUILD=	yes

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_PROJECT=	installer
#GH_TAGNAME=	918e869

.include <bsd.port.mk>
