# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	3gstat
PORTVERSION=	20091215
PORTREVISION=	1
CATEGORIES=	comms
DISTFILES=

MAINTAINER=	franco@opnsense.org
COMMENT=	3G status

PLIST_FILES=	bin/3gstat

do-extract:
	${CP} -r ${FILESDIR} ${WRKSRC}

.include <bsd.port.mk>
