# Created by: Ad Schellevis <ad@opnsense.org>
# $FreeBSD$
PORTNAME=	pam_opnsense
PORTVERSION=	16.7.b
PORTREVISION=	4 # GH_TAGNAME
CATEGORIES=	sysutils

MAINTAINER=	ad@opnsense.org
COMMENT=	OPNsense shared authentication system using PAM

LICENSE=	BSD2CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_TAGNAME=	9679091

.include <bsd.port.mk>
