PORTNAME=	gnatcoll-bindings
DISTVERSIONPREFIX=	v
DISTVERSION=	26.0.0
CATEGORIES=	devel archivers converters lang math science

MAINTAINER=	ada@FreeBSD.org
COMMENT=	GNATColl Bindings meta-port
WWW=		https://github.com/AdaCore/gnatcoll-bindings

LIB_DEPENDS=	libgnatcoll_cpp.so:devel/gnatcoll-bindings-cpp \
		libgnatcoll_gmp.so:devel/gnatcoll-bindings-gmp \
		libgnatcoll_iconv.so:devel/gnatcoll-bindings-iconv \
		libgnatcoll_lzma.so:devel/gnatcoll-bindings-lzma \
		libgnatcoll_omp.so:devel/gnatcoll-bindings-omp \
		libgnatcoll_python3.so:devel/gnatcoll-bindings-python \
		libgnatcoll_readline.so:devel/gnatcoll-bindings-readline \
		libgnatcoll_syslog.so:devel/gnatcoll-bindings-syslog \
		libgnatcoll_zlib.so:devel/gnatcoll-bindings-zlib

USES=		metaport

.include <bsd.port.mk>
