# $Id: Makefile,v 1.5 2005/08/27 02:11:33 cpressey Exp $

BASE?=../../..
include ${BASE}/Config

all:
	@echo "Nothing to build."

clean:
	@echo "No cleaning required."

install:
	mkdir -p ${DESTDIR}${PREFIX}/share/lua/5.0
	cp filename.lua ${DESTDIR}${PREFIX}/share/lua/5.0
