PORTNAME=	dhcrelay
PORTVERSION=	0.2
CATEGORIES=	net

MAINTAINER=	franco@opnsense.org
COMMENT=	OpenBSD dhcrelay daemons
WWW=		https://opnsense.org/

LICENSE=	BSD3CLAUSE

CONFLICTS_INSTALL=	isc-dhcp44-relay

USE_GITHUB=	yes
GH_ACCOUNT=	${CATEGORIES:[1]}
GH_TAGNAME=	8565947

.include <bsd.port.mk>
