# $FreeBSD$

COMMENT=	Security tool to monitor and check logs and intrusions - server installation
OSSEC_TYPE=	server

MASTERDIR=	${.CURDIR}/../ossec-hids-local

USE_HARDENING=	pie:off

.include "${MASTERDIR}/Makefile"
