# Created by: Loic <loic.f@hardenedbsd.org>

PORTNAME=	hardenedbsd-meta
PORTVERSION=	1.0
PORTREVISION=	0
CATEGORIES=	hardenedbsd

MAINTAINER= loic.f@hardenedbsd.org
COMMENT=    meta-port for HardenedBSD

RUN_DEPENDS=	libpushover>=g2020061601:net/libpushover \
		secadm>=0:hardenedbsd/secadm \
		secadm-kmod>=0:hardenedbsd/secadm-kmod \
		hbsdmon>=0:hardenedbsd/hbsdmon

USES=   metaport

.include <bsd.port.mk>
