--- pyproject.toml.orig	2026-09-02 17:43:46 UTC
+++ pyproject.toml
@@ -312,10 +312,8 @@ dev = [
     # after which this can be removed as it is already specified in the
     # [build-system] section
     "scikit-build-core>=1.0",
-    "setuptools>=77.0.0,<82",  # 77.0 is the first release with PEP 639 license-files support
+    "setuptools",  # 77.0 is the first release with PEP 639 license-files support
     "spin",
-    "cmake>=3.27",
-    "ninja",
     "numpy",
     "packaging>=24.2",  # required by setuptools>=77 to validate PEP 639 license expressions
     "pyyaml",
@@ -349,13 +347,6 @@ requires-python = ">=3.10"
 # License info:
 #   - The main Pytorch project license is BSD-3-Clause.
 #   - The SPDX license expression below reflects installed pytorch packages.
-license = "Apache-2.0 AND Apache-2.0 WITH LLVM-exception AND BSD-2-Clause AND BSD-3-Clause AND BSL-1.0 AND MIT"
-license-files = [
-    "LICENSE",
-    "third_party/**/LICENSE",
-    "third_party/**/LICENSE.txt",
-    "third_party/**/LICENSE.rst",
-]
 authors = [{ name = "PyTorch Team", email = "packages@pytorch.org" }]
 keywords = ["pytorch", "machine learning"]
 classifiers = [
