# $Id: Makefile,v 1.6 2005/08/27 02:11:33 cpressey Exp $

BASE?=../../..
include ${BASE}/Config

all:
	@echo "Nothing to build."

clean:
	@echo "No cleaning required."

install:
	mkdir -p ${DESTDIR}${PREFIX}/share/lua/5.0
	cp app.lua ${DESTDIR}${PREFIX}/share/lua/5.0
