# $FreeBSD$

PORTNAME=	apuledctld
PORTVERSION=	1.0

CATEGORIES=	sysutils
MAINTAINER=	alexpro.ewr@gmail.com
COMMENT=	APU onboard leds and button control daemon

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes
GH_ACCOUNT=	alexpro
GH_TAGNAME=	b6efd95

WRKSRC=		${WRKDIR}/apuledctld-${GH_TAGNAME}/apuledctld

.include <bsd.port.mk>
