PORTNAME=	os-update
PORTVERSION=	15.1.6
#PORTREVISION=	1
CATEGORIES=	sysutils
DISTFILES=	# none

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense system update utility

do-extract:
	${CP} -r ${FILESDIR} ${WRKSRC}

.include <bsd.port.mk>
