
PORTNAME=	libpushover
DISTVERSION=	g2021071201
CATEGORIES=	net

MAINTAINER=	shawn.webb@hardenedbsd.org
COMMENT=	Native C API for libpushover

USES=		uidfix

LIB_DEPENDS=	libcurl.so:ftp/curl

USE_GITLAB=	yes
GL_SITE=	https://git.hardenedbsd.org
GL_ACCOUNT=	shawn.webb
GL_PROJECT=	libpushover
GL_COMMIT=	8ecb3b225bf19dfec1b97827a86a710da1e03bb0

.include <bsd.port.mk>

