# Created by: Luca Pizzamiglio <pizzamig@FreeBSD.org>

PKGNAMESUFFIX=	-node14

CONFLICTS_INSTALL=	yarn

OPTIONS_EXCLUDE=	NODE NODE16
OPTIONS_SLAVE=	NODE14

MASTERDIR=	${.CURDIR}/../yarn

.include "${MASTERDIR}/Makefile"
