PORTNAME=	hostwatch
PORTVERSION=	1.0.2
CATEGORIES=	security
DISTFILES=

MAINTAINER=	ad@opnsense.org
COMMENT=	Host discovery daemon

LICENSE=	BSD2CLAUSE

USES=		cargo

PLIST_FILES=	bin/hostwatch

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_TAGNAME=	1.0.2

USE_RC_SUBR=	${PORTNAME}

.include <bsd.port.mk>
