# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	opnsense-lang
PORTVERSION=	16.1.11
PORTREVISION=	2 # GH_TAGNAME set
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense translations

LICENSE=	BSD2CLAUSE

USES=		gettext-tools

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_PROJECT=	lang
GH_TAGNAME=	cf9f57d

.include <bsd.port.mk>
