# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	opnsense-lang
PORTVERSION=	16.7.2
PORTREVISION=	1 # GH_TAGNAME set
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense translations

LICENSE=	BSD2CLAUSE

USES=		gettext-tools

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_PROJECT=	lang
GH_TAGNAME=	6b71c6c

.include <bsd.port.mk>
