# Created by: Franco Fichtner <franco@opnsense.org>
# $FreeBSD$

PORTNAME=	opnsense-lang
PORTVERSION=	16.1.13
CATEGORIES=	sysutils

MAINTAINER=	franco@opnsense.org
COMMENT=	OPNsense translations

LICENSE=	BSD2CLAUSE

USES=		gettext-tools

USE_GITHUB=	yes
GH_ACCOUNT=	opnsense
GH_PROJECT=	lang

.include <bsd.port.mk>
