--- pyproject.toml.orig	2026-06-18 15:35:18 UTC
+++ pyproject.toml
@@ -1,11 +1,11 @@
 [build-system]
-requires = ["setuptools >= 78.1.1"]
+requires = ["setuptools >= 61"]
 build-backend = "setuptools.build_meta"
 
 [project]
 name = "msgpack"
 dynamic = ["version"]
-license = "Apache-2.0"
+license = {text="Apache 2.0"}
 authors = [{name="Inada Naoki", email="songofacandy@gmail.com"}]
 description = "MessagePack serializer"
 readme = "README.md"
